# Generated by Django 5.1 on 2025-11-21 12:36

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0001_initial'),
        ('terminology', '0002_alter_adjunctivetherapyrole_code_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='genomicvariant',
            name='create_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='genomicvariant',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='genomicvariant',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='genomicvariant',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Variant genomic source', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='terminology.geneticvariantsource', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='genomicvariantevent',
            name='source',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Variant genomic source', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='terminology.geneticvariantsource', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='outcome',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('resolved-with-sequelae', 'Resolved With Sequelae'), ('recovering', 'Recovering'), ('ongoing', 'Ongoing'), ('fatal', 'Fatal'), ('unknown', 'Unknown')], help_text='The date when the adverse event ended or returned to baseline.', max_length=50, verbose_name='Date resolved'),
        ),
        migrations.AlterField(
            model_name='adverseeventevent',
            name='outcome',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('resolved-with-sequelae', 'Resolved With Sequelae'), ('recovering', 'Recovering'), ('ongoing', 'Ongoing'), ('fatal', 'Fatal'), ('unknown', 'Unknown')], help_text='The date when the adverse event ended or returned to baseline.', max_length=50, null=True, verbose_name='Date resolved'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='genomicvariant',
            trigger=pgtrigger.compiler.Trigger(name='create_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "oncology_genomicvariantevent" ("allele_depth", "allele_frequency", "analysis_method_id", "assessment", "assessment_date", "case_id", "clinical_relevance", "clinvar", "confidence", "coordinate_system_id", "copy_number", "date", "dna_hgvs", "external_source", "external_source_id", "gene_panel", "genome_assembly_version_id", "id", "inheritance_id", "molecular_consequence_id", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "protein_hgvs", "rna_hgvs", "source_id", "zygosity_id") VALUES (NEW."allele_depth", NEW."allele_frequency", NEW."analysis_method_id", NEW."assessment", NEW."assessment_date", NEW."case_id", NEW."clinical_relevance", NEW."clinvar", NEW."confidence", NEW."coordinate_system_id", NEW."copy_number", NEW."date", NEW."dna_hgvs", NEW."external_source", NEW."external_source_id", NEW."gene_panel", NEW."genome_assembly_version_id", NEW."id", NEW."inheritance_id", NEW."molecular_consequence_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'create\', NEW."id", NEW."protein_hgvs", NEW."rna_hgvs", NEW."source_id", NEW."zygosity_id"); RETURN NULL;', hash='a0b89459eb27850a0b59fa5d353df9a3eefc07a0', operation='INSERT', pgid='pgtrigger_create_insert_9a498', table='oncology_genomicvariant', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='genomicvariant',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "oncology_genomicvariantevent" ("allele_depth", "allele_frequency", "analysis_method_id", "assessment", "assessment_date", "case_id", "clinical_relevance", "clinvar", "confidence", "coordinate_system_id", "copy_number", "date", "dna_hgvs", "external_source", "external_source_id", "gene_panel", "genome_assembly_version_id", "id", "inheritance_id", "molecular_consequence_id", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "protein_hgvs", "rna_hgvs", "source_id", "zygosity_id") VALUES (NEW."allele_depth", NEW."allele_frequency", NEW."analysis_method_id", NEW."assessment", NEW."assessment_date", NEW."case_id", NEW."clinical_relevance", NEW."clinvar", NEW."confidence", NEW."coordinate_system_id", NEW."copy_number", NEW."date", NEW."dna_hgvs", NEW."external_source", NEW."external_source_id", NEW."gene_panel", NEW."genome_assembly_version_id", NEW."id", NEW."inheritance_id", NEW."molecular_consequence_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'update\', NEW."id", NEW."protein_hgvs", NEW."rna_hgvs", NEW."source_id", NEW."zygosity_id"); RETURN NULL;', hash='1a62356df745935071e96d86e5891c5e3a6c6a6a', operation='UPDATE', pgid='pgtrigger_update_update_5a801', table='oncology_genomicvariant', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='genomicvariant',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "oncology_genomicvariantevent" ("allele_depth", "allele_frequency", "analysis_method_id", "assessment", "assessment_date", "case_id", "clinical_relevance", "clinvar", "confidence", "coordinate_system_id", "copy_number", "date", "dna_hgvs", "external_source", "external_source_id", "gene_panel", "genome_assembly_version_id", "id", "inheritance_id", "molecular_consequence_id", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "protein_hgvs", "rna_hgvs", "source_id", "zygosity_id") VALUES (OLD."allele_depth", OLD."allele_frequency", OLD."analysis_method_id", OLD."assessment", OLD."assessment_date", OLD."case_id", OLD."clinical_relevance", OLD."clinvar", OLD."confidence", OLD."coordinate_system_id", OLD."copy_number", OLD."date", OLD."dna_hgvs", OLD."external_source", OLD."external_source_id", OLD."gene_panel", OLD."genome_assembly_version_id", OLD."id", OLD."inheritance_id", OLD."molecular_consequence_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'delete\', OLD."id", OLD."protein_hgvs", OLD."rna_hgvs", OLD."source_id", OLD."zygosity_id"); RETURN NULL;', hash='d25cbd66860435d0d0629ed1a5927e2d7366a9ba', operation='DELETE', pgid='pgtrigger_delete_delete_43385', table='oncology_genomicvariant', when='AFTER')),
        ),
    ]
