# Generated by Django 5.1 on 2025-11-25 10:08

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0002_remove_genomicvariant_create_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='tnmstaging',
            name='create_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='tnmstaging',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='tnmstaging',
            name='delete_delete',
        ),
        migrations.RenameField(
            model_name='tnmstaging',
            old_name='distantMetastases',
            new_name='distant_metastases',
        ),
        migrations.RenameField(
            model_name='tnmstaging',
            old_name='lymphaticInvasion',
            new_name='lymphatic_invasion',
        ),
        migrations.RenameField(
            model_name='tnmstaging',
            old_name='perineuralInvasion',
            new_name='perineural_invasion',
        ),
        migrations.RenameField(
            model_name='tnmstaging',
            old_name='primaryTumor',
            new_name='primary_tumor',
        ),
        migrations.RenameField(
            model_name='tnmstaging',
            old_name='regionalNodes',
            new_name='regional_nodes',
        ),
        migrations.RenameField(
            model_name='tnmstaging',
            old_name='residualTumor',
            new_name='residual_tumor',
        ),
        migrations.RenameField(
            model_name='tnmstaging',
            old_name='serumTumorMarkerLevel',
            new_name='serum_tumor_marker_level',
        ),
        migrations.RenameField(
            model_name='tnmstaging',
            old_name='venousInvasion',
            new_name='venous_invasion',
        ),
        migrations.RenameField(
            model_name='tnmstagingevent',
            old_name='distantMetastases',
            new_name='distant_metastases',
        ),
        migrations.RenameField(
            model_name='tnmstagingevent',
            old_name='lymphaticInvasion',
            new_name='lymphatic_invasion',
        ),
        migrations.RenameField(
            model_name='tnmstagingevent',
            old_name='perineuralInvasion',
            new_name='perineural_invasion',
        ),
        migrations.RenameField(
            model_name='tnmstagingevent',
            old_name='primaryTumor',
            new_name='primary_tumor',
        ),
        migrations.RenameField(
            model_name='tnmstagingevent',
            old_name='regionalNodes',
            new_name='regional_nodes',
        ),
        migrations.RenameField(
            model_name='tnmstagingevent',
            old_name='residualTumor',
            new_name='residual_tumor',
        ),
        migrations.RenameField(
            model_name='tnmstagingevent',
            old_name='serumTumorMarkerLevel',
            new_name='serum_tumor_marker_level',
        ),
        migrations.RenameField(
            model_name='tnmstagingevent',
            old_name='venousInvasion',
            new_name='venous_invasion',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tnmstaging',
            trigger=pgtrigger.compiler.Trigger(name='create_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "oncology_tnmstagingevent" ("distant_metastases_id", "grade_id", "lymphatic_invasion_id", "methodology_id", "pathological", "perineural_invasion_id", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_tumor_id", "regional_nodes_id", "residual_tumor_id", "serum_tumor_marker_level_id", "stage_id", "staging_id", "venous_invasion_id") VALUES (NEW."distant_metastases_id", NEW."grade_id", NEW."lymphatic_invasion_id", NEW."methodology_id", NEW."pathological", NEW."perineural_invasion_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'create\', NEW."staging_id", NEW."primary_tumor_id", NEW."regional_nodes_id", NEW."residual_tumor_id", NEW."serum_tumor_marker_level_id", NEW."stage_id", NEW."staging_id", NEW."venous_invasion_id"); RETURN NULL;', hash='db0ff445fcdf2658f5a8c61cf7a3071ad55bb227', operation='INSERT', pgid='pgtrigger_create_insert_59557', table='oncology_tnmstaging', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tnmstaging',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."distant_metastases_id" IS DISTINCT FROM (NEW."distant_metastases_id") OR OLD."grade_id" IS DISTINCT FROM (NEW."grade_id") OR OLD."lymphatic_invasion_id" IS DISTINCT FROM (NEW."lymphatic_invasion_id") OR OLD."methodology_id" IS DISTINCT FROM (NEW."methodology_id") OR OLD."pathological" IS DISTINCT FROM (NEW."pathological") OR OLD."perineural_invasion_id" IS DISTINCT FROM (NEW."perineural_invasion_id") OR OLD."primary_tumor_id" IS DISTINCT FROM (NEW."primary_tumor_id") OR OLD."regional_nodes_id" IS DISTINCT FROM (NEW."regional_nodes_id") OR OLD."residual_tumor_id" IS DISTINCT FROM (NEW."residual_tumor_id") OR OLD."serum_tumor_marker_level_id" IS DISTINCT FROM (NEW."serum_tumor_marker_level_id") OR OLD."stage_id" IS DISTINCT FROM (NEW."stage_id") OR OLD."staging_id" IS DISTINCT FROM (NEW."staging_id") OR OLD."venous_invasion_id" IS DISTINCT FROM (NEW."venous_invasion_id"))', func='INSERT INTO "oncology_tnmstagingevent" ("distant_metastases_id", "grade_id", "lymphatic_invasion_id", "methodology_id", "pathological", "perineural_invasion_id", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_tumor_id", "regional_nodes_id", "residual_tumor_id", "serum_tumor_marker_level_id", "stage_id", "staging_id", "venous_invasion_id") VALUES (NEW."distant_metastases_id", NEW."grade_id", NEW."lymphatic_invasion_id", NEW."methodology_id", NEW."pathological", NEW."perineural_invasion_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'update\', NEW."staging_id", NEW."primary_tumor_id", NEW."regional_nodes_id", NEW."residual_tumor_id", NEW."serum_tumor_marker_level_id", NEW."stage_id", NEW."staging_id", NEW."venous_invasion_id"); RETURN NULL;', hash='bbf92f65fafbfbd124e1d1ab65e3d81c3def6f71', operation='UPDATE', pgid='pgtrigger_update_update_305ea', table='oncology_tnmstaging', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='tnmstaging',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "oncology_tnmstagingevent" ("distant_metastases_id", "grade_id", "lymphatic_invasion_id", "methodology_id", "pathological", "perineural_invasion_id", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_tumor_id", "regional_nodes_id", "residual_tumor_id", "serum_tumor_marker_level_id", "stage_id", "staging_id", "venous_invasion_id") VALUES (OLD."distant_metastases_id", OLD."grade_id", OLD."lymphatic_invasion_id", OLD."methodology_id", OLD."pathological", OLD."perineural_invasion_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'delete\', OLD."staging_id", OLD."primary_tumor_id", OLD."regional_nodes_id", OLD."residual_tumor_id", OLD."serum_tumor_marker_level_id", OLD."stage_id", OLD."staging_id", OLD."venous_invasion_id"); RETURN NULL;', hash='beb9855f7dfd9be2b5d9c7e87ef45e71fcb8b524', operation='DELETE', pgid='pgtrigger_delete_delete_b65e6', table='oncology_tnmstaging', when='AFTER')),
        ),
    ]
