# Generated by Django 5.1 on 2025-11-27 14:22

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0003_remove_tnmstaging_create_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='familyhistory',
            name='create_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='familyhistory',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='familyhistory',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='is_deceased',
            field=models.BooleanField(blank=True, help_text='Whether the family member is deceased', null=True, verbose_name='Is deceased'),
        ),
        migrations.AddField(
            model_name='familyhistoryevent',
            name='is_deceased',
            field=models.BooleanField(blank=True, help_text='Whether the family member is deceased', null=True, verbose_name='Is deceased'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='familyhistory',
            trigger=pgtrigger.compiler.Trigger(name='create_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "oncology_familyhistoryevent" ("case_id", "contributed_to_death", "date", "external_source", "external_source_id", "had_cancer", "id", "is_deceased", "morphology_id", "onset_age", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_id", "topography_id") VALUES (NEW."case_id", NEW."contributed_to_death", NEW."date", NEW."external_source", NEW."external_source_id", NEW."had_cancer", NEW."id", NEW."is_deceased", NEW."morphology_id", NEW."onset_age", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'create\', NEW."id", NEW."relationship_id", NEW."topography_id"); RETURN NULL;', hash='38109c97fceb07a53e4acb0990a5874fd1787cd9', operation='INSERT', pgid='pgtrigger_create_insert_aba29', table='oncology_familyhistory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='familyhistory',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "oncology_familyhistoryevent" ("case_id", "contributed_to_death", "date", "external_source", "external_source_id", "had_cancer", "id", "is_deceased", "morphology_id", "onset_age", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_id", "topography_id") VALUES (NEW."case_id", NEW."contributed_to_death", NEW."date", NEW."external_source", NEW."external_source_id", NEW."had_cancer", NEW."id", NEW."is_deceased", NEW."morphology_id", NEW."onset_age", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'update\', NEW."id", NEW."relationship_id", NEW."topography_id"); RETURN NULL;', hash='490bfd3241fa3a06742d28c82c6309857c24d724', operation='UPDATE', pgid='pgtrigger_update_update_5220b', table='oncology_familyhistory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='familyhistory',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "oncology_familyhistoryevent" ("case_id", "contributed_to_death", "date", "external_source", "external_source_id", "had_cancer", "id", "is_deceased", "morphology_id", "onset_age", "pgh_context", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_id", "topography_id") VALUES (OLD."case_id", OLD."contributed_to_death", OLD."date", OLD."external_source", OLD."external_source_id", OLD."had_cancer", OLD."id", OLD."is_deceased", OLD."morphology_id", OLD."onset_age", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_id\', TRUE), \'\'), NULL)::UUID, NOW(), \'delete\', OLD."id", OLD."relationship_id", OLD."topography_id"); RETURN NULL;', hash='410f733240a1375182675f7fcc2bd3fde60f5804', operation='DELETE', pgid='pgtrigger_delete_delete_9a6f2', table='oncology_familyhistory', when='AFTER')),
        ),
    ]
