# Generated by Django 5.1 on 2025-11-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctivetherapyrole',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='administrativegender',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='adverseeventmitigationdrug',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='adverseeventmitigationmanagement',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='adverseeventmitigationprocedure',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='adverseeventmitigationtreatmentadjustment',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='adverseeventterm',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='alcoholconsumptionfrequency',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='aminoacidchangetype',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='antineoplasticagent',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='binetstage',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='birthsex',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='bodylocationqualifier',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='breslowdepthstage',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='cancermorphology',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='cancerriskassessmentclassification',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='cancerriskassessmentmethod',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='cancertopography',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='cancertreatmentresponse',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='cancertreatmentresponseobservationmethod',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='causeofdeath',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='chromosomeidentifier',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='clarklevel',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='clinorpathmodifier',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='dnachangetype',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='dosageroute',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='ecogperformancestatusinterpretation',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='expecteddrugaction',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='exposureagent',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='familymembertype',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='figostage',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='figostagingmethod',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='genderidentity',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='geneticvariantsource',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='genomiccoordinatesystem',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='gleasongradegroupstage',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='histologydifferentiation',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='icd10condition',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='karnofskyperformancestatusinterpretation',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='lateralityqualifier',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='lymphomastage',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='lymphomastagevaluemodifier',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='lymphomastagingmethod',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='microsatelliteinstabilitystate',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='molecularconsequence',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='myelomaissstage',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='myelomarissstage',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='neuroblastomainrgssstage',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='neuroblastomainssstage',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='observationbodysite',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='procedureoutcome',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='race',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='radiotherapymodality',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='radiotherapytechnique',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='radiotherapytreatmentlocation',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='radiotherapytreatmentlocationqualifier',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='radiotherapyvolumetype',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='raistage',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='raistagingmethod',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='recreationaldrug',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='referencegenomebuild',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='rhabdomyosarcomaclinicalgroup',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='smokingstatus',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='structuralvariantanalysismethod',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='surgicalprocedure',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmdistantmetastasescategory',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmdistantmetastasesstagingtype',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmgradecategory',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmlymphaticinvasioncategory',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmperineuralinvasioncategory',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmprimarytumorcategory',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmprimarytumorstagingtype',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmregionalnodescategory',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmregionalnodesstagingtype',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmresidualtumorcategory',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmserumtumormarkerlevelcategory',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmstage',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmstagingmethod',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tnmvenousinvasioncategory',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='treatmentterminationreason',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tumorboardrecommendation',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tumormarkeranalyte',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='variantinheritance',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='wilmstumorstage',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='zygosity',
            name='code',
            field=models.CharField(help_text='Code as defined in the code system', max_length=200, verbose_name='Code'),
        ),
    ]
