# Code autogenerated by Fhircraft 0.4.1 on 2025-12-04 08:14:50.581151.

# Fhircraft modules
from fhircraft.fhir.resources.base import FHIRBaseModel, FHIRSliceModel
import fhircraft.fhir.resources.validators as fhir_validators

# Pydantic modules
from pydantic import Field, field_validator, model_validator, BaseModel
from pydantic.fields import FieldInfo

# Standard modules
from typing import Optional, Literal, Union, ClassVar
from enum import Enum

NoneType = type(None)

# Dynamic modules
from fhircraft.fhir.resources.datatypes.R4.core import AdverseEvent
from typing import Annotated, List, Literal, Optional, Union
from fhircraft.fhir.resources.datatypes.R4.complex import (
    DomainResource,
    Address,
    Age,
    Annotation,
    Attachment,
    BackboneElement,
    CodeableConcept,
    Coding,
    ContactDetail,
    ContactPoint,
    Contributor,
    Count,
    DataRequirement,
    Distance,
    Dosage,
    Duration,
    Element,
    Expression,
    Extension,
    HumanName,
    Identifier,
    Meta,
    Money,
    ParameterDefinition,
    Period,
    Quantity,
    Range,
    Ratio,
    Reference,
    RelatedArtifact,
    Resource,
    SampledData,
    Signature,
    Timing,
    TriggerDefinition,
    UsageContext,
)
from fhircraft.fhir.resources.base import FHIRSliceModel
from fhircraft.fhir.resources.datatypes.primitives import (
    Base64Binary,
    Boolean,
    Canonical,
    Code,
    Date,
    DateTime,
    Decimal,
    Id,
    Instant,
    Integer,
    Markdown,
    Oid,
    PositiveInt,
    String,
    Time,
    UnsignedInt,
    Uri,
    Url,
    Uuid,
)
from fhircraft.fhir.resources.validators import (
    get_type_choice_value_by_base,
    validate_element_constraint,
    validate_model_constraint,
    validate_slicing_cardinalities,
    validate_type_choice_element,
)


class AdverseEventCTCGrade(FHIRSliceModel):
    """
    The grade of the adverse event as defined by the Common Terminology Criteria for Adverse Events (CTCAE).
    """

    min_cardinality: ClassVar[int] = 1
    max_cardinality: ClassVar[int] = 1
    id: Optional[String] = Field(
        description="Unique id for inter-element referencing",
        default=None,
    )
    id_ext: Optional[Element] = Field(
        description="Placeholder element for id extensions",
        default=None,
        alias="_id",
    )
    extension: Optional[Extension] = Field(
        description="Extension",
        default=None,
    )
    url: Literal[
        "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-adverse-event-ctc-grade"
    ] = Field(
        description="identifies the meaning of the extension",
        default="http://onconova.github.io/fhir/StructureDefinition/onconova-ext-adverse-event-ctc-grade",
    )
    valueInteger: Optional[Integer] = Field(
        description="CTCAE Grade",
        default=None,
    )
    valueInteger_ext: Optional[Element] = Field(
        description="Placeholder element for valueInteger extensions",
        default=None,
        alias="_valueInteger",
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[Integer],
            field_name_base="value",
            required=False,
        )

    @model_validator(mode="after")
    def FHIR_ele_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ctcae_grade_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="valueInteger() >= 1 and valueInteger() <= 5",
            human="The CTCAE grade must be between 1 and 5, inclusive.",
            key="ctcae-grade",
            severity="error",
        )


class AdverseEventResolvedDate(FHIRSliceModel):
    """
    The date when the adverse event was resolved (if applicable).
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int] = 1
    id: Optional[String] = Field(
        description="Unique id for inter-element referencing",
        default=None,
    )
    id_ext: Optional[Element] = Field(
        description="Placeholder element for id extensions",
        default=None,
        alias="_id",
    )
    extension: Optional[Extension] = Field(
        description="Extension",
        default=None,
    )
    url: Literal[
        "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-adverse-event-resolved-date"
    ] = Field(
        description="identifies the meaning of the extension",
        default="http://onconova.github.io/fhir/StructureDefinition/onconova-ext-adverse-event-resolved-date",
    )
    valueDate: Optional[Date] = Field(
        description="Date resolved",
        default=None,
    )
    valueDate_ext: Optional[Element] = Field(
        description="Placeholder element for valueDate extensions",
        default=None,
        alias="_valueDate",
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[Date],
            field_name_base="value",
            required=False,
        )

    @model_validator(mode="after")
    def FHIR_ele_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ctcae_grade_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="valueInteger() >= 1 and valueInteger() <= 5",
            human="The CTCAE grade must be between 1 and 5, inclusive.",
            key="ctcae-grade",
            severity="error",
        )


class AdverseEventMitigationCategory(Extension, FHIRSliceModel):
    """
    Mitigation Category
    """

    min_cardinality: ClassVar[int] = 1
    max_cardinality: ClassVar[int] = 1
    extension: Optional[Extension] = Field(
        description="Extension",
        default=None,
    )
    url: Literal["category"] = Field(
        description="identifies the meaning of the extension",
        default="category",
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[CodeableConcept],
            field_name_base="value",
            required=False,
        )


class AdverseEventMitigationAdjustment(Extension, FHIRSliceModel):
    """
    Treatment Adjustment
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int] = 1
    extension: Optional[Extension] = Field(
        description="Extension",
        default=None,
    )
    url: Literal["adjustment"] = Field(
        description="identifies the meaning of the extension",
        default="adjustment",
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[CodeableConcept],
            field_name_base="value",
            required=False,
        )


class AdverseEventMitigationDrug(Extension, FHIRSliceModel):
    """
    Mitigation Drug
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int] = 1
    extension: Optional[Extension] = Field(
        description="Extension",
        default=None,
    )
    url: Literal["drug"] = Field(
        description="identifies the meaning of the extension",
        default="drug",
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[CodeableConcept],
            field_name_base="value",
            required=False,
        )


class AdverseEventMitigationProcedure(Extension, FHIRSliceModel):
    """
    Mitigation Procedure
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int] = 1
    extension: Optional[Extension] = Field(
        description="Extension",
        default=None,
    )
    url: Literal["procedure"] = Field(
        description="identifies the meaning of the extension",
        default="procedure",
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[CodeableConcept],
            field_name_base="value",
            required=False,
        )


class AdverseEventMitigationManagement(Extension, FHIRSliceModel):
    """
    Management
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int] = 1
    extension: Optional[Extension] = Field(
        description="Extension",
        default=None,
    )
    url: Literal["management"] = Field(
        description="identifies the meaning of the extension",
        default="management",
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[CodeableConcept],
            field_name_base="value",
            required=False,
        )


class AdverseEventMitigation(FHIRSliceModel):
    """
    Details about an action taken to mitigate or manage the adverse event.
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int] = 99999
    id: Optional[String] = Field(
        description="Unique id for inter-element referencing",
        default=None,
    )
    id_ext: Optional[Element] = Field(
        description="Placeholder element for id extensions",
        default=None,
        alias="_id",
    )
    extension: Optional[
        List[
            Annotated[
                Union[
                    AdverseEventMitigationCategory,
                    AdverseEventMitigationAdjustment,
                    AdverseEventMitigationDrug,
                    AdverseEventMitigationProcedure,
                    AdverseEventMitigationManagement,
                    Extension,
                ],
                Field(union_mode="left_to_right"),
            ]
        ]
    ] = Field(
        description="Extension",
        default=None,
    )
    url: Literal[
        "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-adverse-event-mitigation"
    ] = Field(
        description="identifies the meaning of the extension",
        default="http://onconova.github.io/fhir/StructureDefinition/onconova-ext-adverse-event-mitigation",
    )
    valueBase64Binary: Optional[Base64Binary] = Field(
        description="Value of extension",
        default=None,
    )
    valueBase64Binary_ext: Optional[Element] = Field(
        description="Placeholder element for valueBase64Binary extensions",
        default=None,
        alias="_valueBase64Binary",
    )
    valueBoolean: Optional[Boolean] = Field(
        description="Value of extension",
        default=None,
    )
    valueBoolean_ext: Optional[Element] = Field(
        description="Placeholder element for valueBoolean extensions",
        default=None,
        alias="_valueBoolean",
    )
    valueCanonical: Optional[Canonical] = Field(
        description="Value of extension",
        default=None,
    )
    valueCanonical_ext: Optional[Element] = Field(
        description="Placeholder element for valueCanonical extensions",
        default=None,
        alias="_valueCanonical",
    )
    valueCode: Optional[Code] = Field(
        description="Value of extension",
        default=None,
    )
    valueCode_ext: Optional[Element] = Field(
        description="Placeholder element for valueCode extensions",
        default=None,
        alias="_valueCode",
    )
    valueDate: Optional[Date] = Field(
        description="Value of extension",
        default=None,
    )
    valueDate_ext: Optional[Element] = Field(
        description="Placeholder element for valueDate extensions",
        default=None,
        alias="_valueDate",
    )
    valueDateTime: Optional[DateTime] = Field(
        description="Value of extension",
        default=None,
    )
    valueDateTime_ext: Optional[Element] = Field(
        description="Placeholder element for valueDateTime extensions",
        default=None,
        alias="_valueDateTime",
    )
    valueDecimal: Optional[Decimal] = Field(
        description="Value of extension",
        default=None,
    )
    valueDecimal_ext: Optional[Element] = Field(
        description="Placeholder element for valueDecimal extensions",
        default=None,
        alias="_valueDecimal",
    )
    valueId: Optional[Id] = Field(
        description="Value of extension",
        default=None,
    )
    valueId_ext: Optional[Element] = Field(
        description="Placeholder element for valueId extensions",
        default=None,
        alias="_valueId",
    )
    valueInstant: Optional[Instant] = Field(
        description="Value of extension",
        default=None,
    )
    valueInstant_ext: Optional[Element] = Field(
        description="Placeholder element for valueInstant extensions",
        default=None,
        alias="_valueInstant",
    )
    valueInteger: Optional[Integer] = Field(
        description="Value of extension",
        default=None,
    )
    valueInteger_ext: Optional[Element] = Field(
        description="Placeholder element for valueInteger extensions",
        default=None,
        alias="_valueInteger",
    )
    valueMarkdown: Optional[Markdown] = Field(
        description="Value of extension",
        default=None,
    )
    valueMarkdown_ext: Optional[Element] = Field(
        description="Placeholder element for valueMarkdown extensions",
        default=None,
        alias="_valueMarkdown",
    )
    valueOid: Optional[Oid] = Field(
        description="Value of extension",
        default=None,
    )
    valueOid_ext: Optional[Element] = Field(
        description="Placeholder element for valueOid extensions",
        default=None,
        alias="_valueOid",
    )
    valuePositiveInt: Optional[PositiveInt] = Field(
        description="Value of extension",
        default=None,
    )
    valuePositiveInt_ext: Optional[Element] = Field(
        description="Placeholder element for valuePositiveInt extensions",
        default=None,
        alias="_valuePositiveInt",
    )
    valueString: Optional[String] = Field(
        description="Value of extension",
        default=None,
    )
    valueString_ext: Optional[Element] = Field(
        description="Placeholder element for valueString extensions",
        default=None,
        alias="_valueString",
    )
    valueTime: Optional[Time] = Field(
        description="Value of extension",
        default=None,
    )
    valueTime_ext: Optional[Element] = Field(
        description="Placeholder element for valueTime extensions",
        default=None,
        alias="_valueTime",
    )
    valueUnsignedInt: Optional[UnsignedInt] = Field(
        description="Value of extension",
        default=None,
    )
    valueUnsignedInt_ext: Optional[Element] = Field(
        description="Placeholder element for valueUnsignedInt extensions",
        default=None,
        alias="_valueUnsignedInt",
    )
    valueUri: Optional[Uri] = Field(
        description="Value of extension",
        default=None,
    )
    valueUri_ext: Optional[Element] = Field(
        description="Placeholder element for valueUri extensions",
        default=None,
        alias="_valueUri",
    )
    valueUrl: Optional[Url] = Field(
        description="Value of extension",
        default=None,
    )
    valueUrl_ext: Optional[Element] = Field(
        description="Placeholder element for valueUrl extensions",
        default=None,
        alias="_valueUrl",
    )
    valueUuid: Optional[Uuid] = Field(
        description="Value of extension",
        default=None,
    )
    valueUuid_ext: Optional[Element] = Field(
        description="Placeholder element for valueUuid extensions",
        default=None,
        alias="_valueUuid",
    )
    valueAddress: Optional[Address] = Field(
        description="Value of extension",
        default=None,
    )
    valueAge: Optional[Age] = Field(
        description="Value of extension",
        default=None,
    )
    valueAnnotation: Optional[Annotation] = Field(
        description="Value of extension",
        default=None,
    )
    valueAttachment: Optional[Attachment] = Field(
        description="Value of extension",
        default=None,
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension",
        default=None,
    )
    valueCoding: Optional[Coding] = Field(
        description="Value of extension",
        default=None,
    )
    valueContactPoint: Optional[ContactPoint] = Field(
        description="Value of extension",
        default=None,
    )
    valueCount: Optional[Count] = Field(
        description="Value of extension",
        default=None,
    )
    valueDistance: Optional[Distance] = Field(
        description="Value of extension",
        default=None,
    )
    valueDuration: Optional[Duration] = Field(
        description="Value of extension",
        default=None,
    )
    valueHumanName: Optional[HumanName] = Field(
        description="Value of extension",
        default=None,
    )
    valueIdentifier: Optional[Identifier] = Field(
        description="Value of extension",
        default=None,
    )
    valueMoney: Optional[Money] = Field(
        description="Value of extension",
        default=None,
    )
    valuePeriod: Optional[Period] = Field(
        description="Value of extension",
        default=None,
    )
    valueQuantity: Optional[Quantity] = Field(
        description="Value of extension",
        default=None,
    )
    valueRange: Optional[Range] = Field(
        description="Value of extension",
        default=None,
    )
    valueRatio: Optional[Ratio] = Field(
        description="Value of extension",
        default=None,
    )
    valueReference: Optional[Reference] = Field(
        description="Value of extension",
        default=None,
    )
    valueSampledData: Optional[SampledData] = Field(
        description="Value of extension",
        default=None,
    )
    valueSignature: Optional[Signature] = Field(
        description="Value of extension",
        default=None,
    )
    valueTiming: Optional[Timing] = Field(
        description="Value of extension",
        default=None,
    )
    valueContactDetail: Optional[ContactDetail] = Field(
        description="Value of extension",
        default=None,
    )
    valueContributor: Optional[Contributor] = Field(
        description="Value of extension",
        default=None,
    )
    valueDataRequirement: Optional[DataRequirement] = Field(
        description="Value of extension",
        default=None,
    )
    valueExpression: Optional[Expression] = Field(
        description="Value of extension",
        default=None,
    )
    valueParameterDefinition: Optional[ParameterDefinition] = Field(
        description="Value of extension",
        default=None,
    )
    valueRelatedArtifact: Optional[RelatedArtifact] = Field(
        description="Value of extension",
        default=None,
    )
    valueTriggerDefinition: Optional[TriggerDefinition] = Field(
        description="Value of extension",
        default=None,
    )
    valueUsageContext: Optional[UsageContext] = Field(
        description="Value of extension",
        default=None,
    )
    valueDosage: Optional[Dosage] = Field(
        description="Value of extension",
        default=None,
    )
    valueMeta: Optional[Meta] = Field(
        description="Value of extension",
        default=None,
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="extension",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[
                Base64Binary,
                Boolean,
                Canonical,
                Code,
                Date,
                DateTime,
                Decimal,
                Id,
                Instant,
                Integer,
                Markdown,
                Oid,
                PositiveInt,
                String,
                Time,
                UnsignedInt,
                Uri,
                Url,
                Uuid,
                Address,
                Age,
                Annotation,
                Attachment,
                CodeableConcept,
                Coding,
                ContactPoint,
                Count,
                Distance,
                Duration,
                HumanName,
                Identifier,
                Money,
                Period,
                Quantity,
                Range,
                Ratio,
                Reference,
                SampledData,
                Signature,
                Timing,
                ContactDetail,
                Contributor,
                DataRequirement,
                Expression,
                ParameterDefinition,
                RelatedArtifact,
                TriggerDefinition,
                UsageContext,
                Dosage,
                Meta,
            ],
            field_name_base="value",
            required=False,
        )

    @model_validator(mode="after")
    def FHIR_ele_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_drug_mitigation_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="extension('category').valueCodeableConcept.coding.code = 'C49158' implies (extension('drug').exists() and not extension('procedure').exists() and not extension('adjustment').exists())",
            human="If the mitigation category is 'Drug', then only mitigation drug must be specified.",
            key="drug-mitigation",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_adjustment_mitigation_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="extension('category').valueCodeableConcept.coding.code = 'C49157' implies (extension('adjustment').exists() and not extension('procedure').exists() and not extension('drug').exists())",
            human="If the mitigation category is 'Adjustment', then only mitigation adjustment must be specified.",
            key="adjustment-mitigation",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_procedural_mitigation_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="extension('category').valueCodeableConcept.coding.code = 'C49159' implies (extension('procedure').exists() and not extension('adjustment').exists() and not extension('drug').exists())",
            human="If the mitigation category is 'Procedure', then only mitigation procedure must be specified.",
            key="procedural-mitigation",
            severity="error",
        )


class OnconovaAdverseEventSuspectEntityCausality(BackboneElement):
    """
    Information on the possible cause of the event.
    """

    assessment: Optional[CodeableConcept] = Field(
        description="Assessment of if the entity caused the event",
        default=None,
    )
    productRelatedness: Optional[String] = Field(
        description="AdverseEvent.suspectEntity.causalityProductRelatedness",
        default=None,
    )
    productRelatedness_ext: Optional[Element] = Field(
        description="Placeholder element for productRelatedness extensions",
        default=None,
        alias="_productRelatedness",
    )
    author: Optional[Reference] = Field(
        description="AdverseEvent.suspectEntity.causalityAuthor",
        default=None,
    )
    method: Optional[CodeableConcept] = Field(
        description="ProbabilityScale | Bayesian | Checklist",
        default=None,
    )

    @field_validator(
        *(
            "method",
            "author",
            "productRelatedness",
            "assessment",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
        ),
        mode="after",
        check_fields=None
    )
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )


class OnconovaAdverseEventSuspectEntity(BackboneElement):
    """
    Describes the entity that is suspected to have caused the adverse event.
    """

    instance: Optional[Reference] = Field(
        description="Refers to the specific entity that caused the adverse event",
        default=None,
    )
    causality: Optional[List[OnconovaAdverseEventSuspectEntityCausality]] = Field(
        description="Information on the possible cause of the event",
        default=None,
    )

    @field_validator(
        *(
            "causality",
            "instance",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
        ),
        mode="after",
        check_fields=None
    )
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )


class OnconovaAdverseEvent(AdverseEvent):
    """
        A profile representing an adverse event experienced by a cancer patient as a result of an antineoplastic treatment, structured according to the Common Terminology Criteria for Adverse Events (CTCAE). This resource is used to capture and standardize the documentation of adverse events occurring during cancer care, including the type of event, its CTCAE grade, and any mitigation actions taken.

    The profile constrains the base FHIR `AdverseEvent` resource to ensure consistent use of CTCAE codes and grades, and supports linkage to related treatments such as medications, radiotherapy, or surgical procedures documented in Onconova. The profile also provides extensions for recording mitigation strategies, supporting detailed tracking and management of adverse events in cancer patients.

    **Conformance:**

    AdverseEvent resources representing an adverse event caused by a cancer therapy in the scope of Onconova SHALL conform to this profile. Any resource intended to conform to this profile SHOULD populate `meta.profile` accordingly.
    """

    meta: Optional[Meta] = Field(
        title="Meta",
        description="Metadata about the resource.",
        default_factory=lambda: Meta(
            profile=[
                "http://onconova.github.io/fhir/StructureDefinition/onconova-adverse-event"
            ]
        ),
    )
    contained: Optional[List[Resource]] = Field(
        description="Contained, inline Resources",
        default=None,
    )
    extension: Optional[
        List[
            Annotated[
                Union[
                    AdverseEventCTCGrade,
                    AdverseEventResolvedDate,
                    AdverseEventMitigation,
                    Extension,
                ],
                Field(union_mode="left_to_right"),
            ]
        ]
    ] = Field(
        description="Extension",
        default=None,
    )
    modifierExtension: Optional[List[Extension]] = Field(
        description="Extensions that cannot be ignored",
        default=None,
    )
    actuality: Optional[Code] = Field(
        description="Not used in this profile",
        default=None,
    )
    category: Optional[List[CodeableConcept]] = Field(
        description="Not used in this profile",
        default=None,
    )
    encounter: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    detected: Optional[DateTime] = Field(
        description="Not used in this profile",
        default=None,
    )
    recordedDate: Optional[DateTime] = Field(
        description="Not used in this profile",
        default=None,
    )
    resultingCondition: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    location: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    seriousness: Optional[CodeableConcept] = Field(
        description="Not used in this profile",
        default=None,
    )
    severity: Optional[CodeableConcept] = Field(
        description="Not used in this profile",
        default=None,
    )
    recorder: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    contributor: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    suspectEntity: Optional[List[OnconovaAdverseEventSuspectEntity]] = Field(
        description="The suspected agent causing the adverse event",
        default=None,
    )
    subjectMedicalHistory: Optional[List[Reference]] = Field(
        description="AdverseEvent.subjectMedicalHistory",
        default=None,
    )
    referenceDocument: Optional[List[Reference]] = Field(
        description="AdverseEvent.referenceDocument",
        default=None,
    )
    study: Optional[List[Reference]] = Field(
        description="AdverseEvent.study",
        default=None,
    )

    @field_validator(
        *(
            "study",
            "referenceDocument",
            "subjectMedicalHistory",
            "suspectEntity",
            "contributor",
            "recorder",
            "outcome",
            "severity",
            "seriousness",
            "location",
            "resultingCondition",
            "recordedDate",
            "detected",
            "date",
            "encounter",
            "subject",
            "event",
            "category",
            "actuality",
            "identifier",
            "modifierExtension",
            "extension",
            "text",
            "language",
            "implicitRules",
            "meta",
        ),
        mode="after",
        check_fields=None
    )
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(
        *("modifierExtension", "extension"), mode="after", check_fields=None
    )
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="extension",
        )

    @model_validator(mode="after")
    def FHIR_dom_2_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="contained.contained.empty()",
            human="If the resource is contained in another resource, it SHALL NOT contain nested Resources",
            key="dom-2",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_dom_3_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="contained.where((('#'+id in (%resource.descendants().reference | %resource.descendants().ofType(canonical) | %resource.descendants().ofType(uri) | %resource.descendants().ofType(url))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(canonical) = '#').exists()).not()).trace('unmatched', id).empty()",
            human="If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
            key="dom-3",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_dom_4_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
            human="If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
            key="dom-4",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_dom_5_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="contained.meta.security.empty()",
            human="If a resource is contained in another resource, it SHALL NOT have a security label",
            key="dom-5",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_dom_6_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="text.`div`.exists()",
            human="A resource should have narrative for robust management",
            key="dom-6",
            severity="warning",
        )

    @model_validator(mode="after")
    def FHIR_ae_req_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="subject.exists()",
            human="The subject element is required and must be provided.",
            key="ae-req-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ae_req_2_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="date.exists() and date.hasValue()",
            human="The date element is required and must be provided.",
            key="ae-req-2",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ae_req_3_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="event.exists() and event.coding.exists()",
            human="The event element is required and must be provided.",
            key="ae-req-3",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ae_req_4_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="extension('http://onconova.github.io/fhir/StructureDefinition/onconova-ext-adverse-event-ctc-grade').exists()",
            human="The CTC Grade extension is required and must be provided.",
            key="ae-req-4",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ae_req_5_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="outcome.exists() and outcome.coding.exists()",
            human="The outcome is required and must be provided.",
            key="ae-req-5",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ae_req_6_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="suspectEntity.exists() implies (suspectEntity.count() > 0 and suspectEntity.instance.exists())",
            human="If suspectedEntity is provided, then at least one instance must exist.",
            key="ae-req-6",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ae_req_7_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="extension('http://onconova.github.io/fhir/StructureDefinition/onconova-ext-adverse-event-mitigation').exists() implies extension('http://onconova.github.io/fhir/StructureDefinition/onconova-ext-adverse-event-mitigation').count() > 0",
            human="If adverseEventMitigation extension is provided, then at least one instance must exist.",
            key="ae-req-7",
            severity="error",
        )
