# Code autogenerated by Fhircraft 0.5.0 on 2026-04-15 15:32:51.395994.
# pyright: reportIncompatibleVariableOverride=false

from fhircraft.fhir.resources.datatypes.R4.core.observation import Observation, ObservationComponent, ObservationReferenceRange
from typing import Annotated, ClassVar, List, Optional, Union
from fhircraft.fhir.resources.datatypes.R4.complex import Address, Age, Annotation, Attachment, CodeableConcept, Coding, ContactDetail, ContactPoint, Contributor, Count, DataRequirement, Distance, Dosage, Duration, Expression, Extension, HumanName, Identifier, Meta, Money, ParameterDefinition, Period, Quantity, Range, Ratio, Reference, RelatedArtifact, SampledData, Signature, Timing, TriggerDefinition, UsageContext
from fhircraft.fhir.resources.base import FHIRSliceModel, FhirBaseModelKind
from pydantic import Field, field_validator, model_validator
from fhircraft.fhir.resources.validators import get_type_choice_value_by_base, validate_FHIR_element_fixed_value, validate_FHIR_element_pattern, validate_element_constraint, validate_model_constraint, validate_slicing_cardinalities, validate_type_choice_element
from fhircraft.fhir.resources.datatypes.R4.primitive import Base64Binary, Boolean, Canonical, Code, Date, DateTime, Decimal, Id, Instant, Integer, Markdown, Oid, PositiveInt, String, Time, UnsignedInt, Uri, Url, Uuid
import fhircraft.fhir.resources.datatypes.R4.primitive as fhir
NoneType = type(None)

 
class USCoreSimpleObservationProfileUsCore(CodeableConcept, FHIRSliceModel):
    """
    A code that classifies the general type of observation being made.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None


    pass
    
 
class USCoreSimpleObservationProfile(Observation):
    """
    assessment observation
    """

    _abstract = True
    _canonical_url = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-simple-observation"

    status: Optional[fhir.code] = Field(
        description="The status of the result value.",
        default=None,
    )
    category: Optional[List[Union[USCoreSimpleObservationProfileUsCore, CodeableConcept]]] = Field(
        description="(USCDI) Classification of  type of observation",
        default=None,
    )
    code: Optional[CodeableConcept] = Field(
        description="Describes what was observed. Sometimes this is called the observation \"name\".",
        default=None,
    )
    subject: Optional[Reference] = Field(
        description="The patient, or group of patients, location, or device this observation is about and into whose record the observation is placed. If the actual focus of the observation is different from the subject (or a sample of, part, or region of the subject), the `focus` element or the `code` itself specifies the actual focus of the observation.",
        default=None,
    )
    effectiveDateTime: Optional[fhir.dateTime] = Field(
        description="The time or time-period the observed value is asserted as being true. For biological subjects - e.g. human patients - this is usually called the \"physiologically relevant time\".",
        default=None,
    )
    effectivePeriod: Optional[Period] = Field(
        description="The time or time-period the observed value is asserted as being true. For biological subjects - e.g. human patients - this is usually called the \"physiologically relevant time\".",
        default=None,
    )
    effectiveTiming: Optional[Timing] = Field(
        description="The time or time-period the observed value is asserted as being true. For biological subjects - e.g. human patients - this is usually called the \"physiologically relevant time\".",
        default=None,
    )
    effectiveInstant: Optional[fhir.instant] = Field(
        description="The time or time-period the observed value is asserted as being true. For biological subjects - e.g. human patients - this is usually called the \"physiologically relevant time\".",
        default=None,
    )
    performer: Optional[List[Reference]] = Field(
        description="Who was responsible for asserting the observed value as \"true\".",
        default=None,
    )
    valueQuantity: Optional[Quantity] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueString: Optional[fhir.string] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueBoolean: Optional[fhir.boolean] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueInteger: Optional[fhir.integer] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueRange: Optional[Range] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueRatio: Optional[Ratio] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueSampledData: Optional[SampledData] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueTime: Optional[fhir.time_] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueDateTime: Optional[fhir.dateTime] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valuePeriod: Optional[Period] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    derivedFrom: Optional[List[Reference]] = Field(
        description="US Core Observations, DocumentReference, QuestionnaireResponse or other resource from which this observation value is derived.",
        default=None,
    )
    
    @property 
    def effective(self):
        return get_type_choice_value_by_base(self, 
            base="effective",
        )
        
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('category',), mode="after", check_fields=None)
    @classmethod
    def category_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="category",
        )
        
    @model_validator(mode="after")
    def effective_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['DateTime', 'Period', 'Timing', 'Instant'],
            field_name_base="effective",
            required=False,
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['Quantity', 'CodeableConcept', 'String', 'Boolean', 'Integer', 'Range', 'Ratio', 'SampledData', 'Time', 'DateTime', 'Period'],
            field_name_base="value",
            required=False,
        )
        
    @model_validator(mode="after")
    def FHIR_obs_6_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='dataAbsentReason.empty() or value.empty()',
            human='dataAbsentReason SHALL only be present if Observation.value[x] is not present',
            key='obs-6',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_obs_7_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='value.empty() or component.code.where(coding.intersect(%resource.code.coding).exists()).empty()',
            human='If Observation.code is the same as an Observation.component.code then the value element associated with the code SHALL NOT be present',
            key='obs-7',
            severity='error',
        )
        
 
class RelatedCondition(Extension):
    """
    A condition that has a relationship with the resource.
    """

    _abstract = True
    _canonical_url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: 'http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition',
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueReference: Optional[Reference] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @field_validator(*('url',), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):    
        return validate_FHIR_element_fixed_value(cls, value, 
            constant='http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition',
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept', 'Reference'],
            field_name_base="value",
            required=True,
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class ComorbiditiesComorbidConditionPresent(RelatedCondition, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None


    pass
    
    @model_validator(mode="after")
    def FHIR_ele_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='hasValue() or (children().count() > id.count())',
            human='All FHIR elements must have a @value or children',
            key='ele-1',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class RelatedConditionAbsent(Extension):
    """
    A condition that is NOT present, related to the resource.
    """

    _abstract = True
    _canonical_url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: 'http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent',
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @field_validator(*('url',), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):    
        return validate_FHIR_element_fixed_value(cls, value, 
            constant='http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition-absent',
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=True,
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class ComorbiditiesComorbidConditionAbsent(RelatedConditionAbsent, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None


    pass
    
    @model_validator(mode="after")
    def FHIR_ele_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='hasValue() or (children().count() > id.count())',
            human='All FHIR elements must have a @value or children',
            key='ele-1',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class Comorbidities(USCoreSimpleObservationProfile):
    """
    assessment observation
    """

    _canonical_url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-comorbidities"

    extension: Optional[List[Union[ComorbiditiesComorbidConditionPresent, ComorbiditiesComorbidConditionAbsent, Extension]]] = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    code: Optional[CodeableConcept] = Field(
        description="Describes what was observed. Sometimes this is called the observation \"name\".",
        default_factory=lambda: CodeableConcept(coding=[Coding(code='398192003', system='http://snomed.info/sct')]),
    )
    subject: Optional[Reference] = Field(
        description="The patient whose comorbidities are recorded.",
        default=None,
    )
    focus: Optional[List[Reference]] = Field(
        description="Comorbid conditions are typically defined with respect to a specific \u0027index\u0027 condition. For example, the US Centers for Disease Control (CDC) has provided a list of comorbid conditions important to COVID-19. In this case, the focus would be COVID-19 and the comorbid condition categories would be those specified by CDC, namely obesity, renal disease, respiratory disease, etc.",
        default=None,
    )
    valueQuantity: Optional[Quantity] = Field(
        description="Comorbidity score or risk index",
        default=None,
    )
    valueInteger: Optional[fhir.integer] = Field(
        description="Comorbidity score or risk index",
        default=None,
    )
    bodySite: Optional[CodeableConcept] = Field(
        description="Not used in this profile",
        default=None,
    )
    method: Optional[CodeableConcept] = Field(
        description="The formal methodology used, such as Charlson, NCI, Elixhauser, or ACE-27. The method must be specified if a comorbidity index is specified, otherwise the index cannot be correctly interpreted.",
        default=None,
    )
    specimen: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    device: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    hasMember: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    component: Optional[List[ObservationComponent]] = Field(
        description="Not used in this profile",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @field_validator(*('code',), mode="after", check_fields=None)
    @classmethod
    def FHIR_code_pattern_constraint(cls, value):    
        return validate_FHIR_element_pattern(cls, value, 
            pattern=CodeableConcept(coding=[Coding(code='398192003', system='http://snomed.info/sct')]),
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['Quantity', 'Integer'],
            field_name_base="value",
            required=False,
        )
        
    @model_validator(mode="after")
    def FHIR_obs_6_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='dataAbsentReason.empty() or value.empty()',
            human='dataAbsentReason SHALL only be present if Observation.value[x] is not present',
            key='obs-6',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_obs_7_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='value.empty() or component.code.where(coding.intersect(%resource.code.coding).exists()).empty()',
            human='If Observation.code is the same as an Observation.component.code then the value element associated with the code SHALL NOT be present',
            key='obs-7',
            severity='error',
        )
        
 
class OnconovaComorbiditiesComorbidConditionPresent(Extension, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None


    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @model_validator(mode="after")
    def FHIR_ele_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='hasValue() or (children().count() > id.count())',
            human='All FHIR elements must have a @value or children',
            key='ele-1',
            severity='error',
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=False,
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class OnconovaComorbiditiesComorbidConditionAbsent(Extension, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None


    valueBase64Binary: Optional[fhir.base64Binary] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueBoolean: Optional[fhir.boolean] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueCanonical: Optional[fhir.canonical] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueCode: Optional[fhir.code] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDate: Optional[fhir.date_] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDateTime: Optional[fhir.dateTime] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDecimal: Optional[fhir.decimal] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueId: Optional[fhir.id_] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueInstant: Optional[fhir.instant] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueInteger: Optional[fhir.integer] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueMarkdown: Optional[fhir.markdown] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueOid: Optional[fhir.oid] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valuePositiveInt: Optional[fhir.positiveInt] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueString: Optional[fhir.string] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueTime: Optional[fhir.time_] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueUnsignedInt: Optional[fhir.unsignedInt] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueUri: Optional[fhir.uri] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueUrl: Optional[fhir.url] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueUuid: Optional[fhir.uuid] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueAddress: Optional[Address] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueAge: Optional[Age] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueAnnotation: Optional[Annotation] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueAttachment: Optional[Attachment] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueCoding: Optional[Coding] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueContactPoint: Optional[ContactPoint] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueCount: Optional[Count] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDistance: Optional[Distance] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDuration: Optional[Duration] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueHumanName: Optional[HumanName] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueIdentifier: Optional[Identifier] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueMoney: Optional[Money] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valuePeriod: Optional[Period] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueQuantity: Optional[Quantity] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueRange: Optional[Range] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueRatio: Optional[Ratio] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueReference: Optional[Reference] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueSampledData: Optional[SampledData] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueSignature: Optional[Signature] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueTiming: Optional[Timing] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueContactDetail: Optional[ContactDetail] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueContributor: Optional[Contributor] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDataRequirement: Optional[DataRequirement] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueExpression: Optional[Expression] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueParameterDefinition: Optional[ParameterDefinition] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueRelatedArtifact: Optional[RelatedArtifact] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueTriggerDefinition: Optional[TriggerDefinition] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueUsageContext: Optional[UsageContext] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDosage: Optional[Dosage] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueMeta: Optional[Meta] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @model_validator(mode="after")
    def FHIR_ele_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='hasValue() or (children().count() > id.count())',
            human='All FHIR elements must have a @value or children',
            key='ele-1',
            severity='error',
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['Base64Binary', 'Boolean', 'Canonical', 'Code', 'Date', 'DateTime', 'Decimal', 'Id', 'Instant', 'Integer', 'Markdown', 'Oid', 'PositiveInt', 'String', 'Time', 'UnsignedInt', 'Uri', 'Url', 'Uuid', 'Address', 'Age', 'Annotation', 'Attachment', 'CodeableConcept', 'Coding', 'ContactPoint', 'Count', 'Distance', 'Duration', 'HumanName', 'Identifier', 'Money', 'Period', 'Quantity', 'Range', 'Ratio', 'Reference', 'SampledData', 'Signature', 'Timing', 'ContactDetail', 'Contributor', 'DataRequirement', 'Expression', 'ParameterDefinition', 'RelatedArtifact', 'TriggerDefinition', 'UsageContext', 'Dosage', 'Meta'],
            field_name_base="value",
            required=False,
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class OnconovaComorbiditiesValueQuantity(Quantity):
    """
    Comorbidity score or risk index
    """


    unit: Optional[fhir.string] = Field(
        description="A human-readable form of the unit.",
        default_factory=lambda: '1',
    )
    
    @field_validator(*('unit',), mode="after", check_fields=None)
    @classmethod
    def FHIR_unit_pattern_constraint(cls, value):    
        return validate_FHIR_element_pattern(cls, value, 
            pattern='1',
        )
        
 
class OnconovaComorbidities(Comorbidities):
    """
    assessment observation
    """

    _canonical_url = "http://onconova.github.io/fhir/StructureDefinition/onconova-comorbidities"

    extension: Optional[List[Union[ComorbiditiesComorbidConditionPresent, ComorbiditiesComorbidConditionAbsent, OnconovaComorbiditiesComorbidConditionPresent, OnconovaComorbiditiesComorbidConditionAbsent, Extension]]] = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    basedOn: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    partOf: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    status: Optional[fhir.code] = Field(
        description="Not used in this profile",
        default=None,
    )
    focus: Optional[List[Reference]] = Field(
        description="Comorbid conditions are typically defined with respect to a specific \u0027index\u0027 condition. For example, the US Centers for Disease Control (CDC) has provided a list of comorbid conditions important to COVID-19. In this case, the focus would be COVID-19 and the comorbid condition categories would be those specified by CDC, namely obesity, renal disease, respiratory disease, etc.",
        default=None,
    )
    encounter: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    issued: Optional[fhir.instant] = Field(
        description="Not used in this profile",
        default=None,
    )
    performer: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    valueQuantity: Optional[OnconovaComorbiditiesValueQuantity] = Field(
        description="Comorbidity score or risk index",
        default=None,
    )
    interpretation: Optional[List[CodeableConcept]] = Field(
        description="Not used in this profile",
        default=None,
    )
    referenceRange: Optional[List[ObservationReferenceRange]] = Field(
        description="Not used in this profile",
        default=None,
    )
    derivedFrom: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    
    @property 
    def effective(self):
        return get_type_choice_value_by_base(self, 
            base="effective",
        )
        
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @model_validator(mode="after")
    def effective_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['DateTime'],
            field_name_base="effective",
            required=True,
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['Quantity'],
            field_name_base="value",
            required=False,
        )
        
    @model_validator(mode="after")
    def FHIR_obs_3_constraint_validator(self):
        return validate_element_constraint( 
            self,
            elements="referenceRange",
            expression='low.exists() or high.exists() or text.exists()',
            human='Must have at least a low or a high or text',
            key='obs-3',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_com_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='valueQuantity.exists() implies method.exists()',
            human='If an index score is provided, then the comorbidity panel method must also be provided.',
            key='com-1',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_com_req_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='subject.exists()',
            human='The subject element is required and must be provided.',
            key='com-req-1',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_com_req_2_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='effectiveDateTime.exists() and effectiveDateTime.hasValue()',
            human='The effectiveDateTime element is required and must be provided.',
            key='com-req-2',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_com_req_3_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='focus.exists()',
            human='The focus element is required and must be provided.',
            key='com-req-3',
            severity='error',
        )
        
