# Code autogenerated by Fhircraft 0.5.0 on 2026-04-15 15:32:49.568488.
# pyright: reportIncompatibleVariableOverride=false

from fhircraft.fhir.resources.datatypes.R4.core.observation import Observation, ObservationComponent, ObservationReferenceRange
from typing import Annotated, ClassVar, List, Optional, Union
from fhircraft.fhir.resources.datatypes.R4.complex import CodeableConcept, Coding, Period, Quantity, Range, Ratio, Reference, SampledData, Timing
from fhircraft.fhir.resources.base import FHIRSliceModel, FhirBaseModelKind
from pydantic import Field, field_validator, model_validator
from fhircraft.fhir.resources.validators import get_type_choice_value_by_base, validate_FHIR_element_pattern, validate_element_constraint, validate_model_constraint, validate_slicing_cardinalities, validate_type_choice_element
from fhircraft.fhir.resources.datatypes.R4.primitive import Boolean, DateTime, Instant, Integer, String, Time
import fhircraft.fhir.resources.datatypes.R4.primitive as fhir
NoneType = type(None)

 
class USCoreSimpleObservationProfileUsCore(CodeableConcept, FHIRSliceModel):
    """
    A code that classifies the general type of observation being made.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None


    pass
    
 
class USCoreSimpleObservationProfile(Observation):
    """
    assessment observation
    """

    _abstract = True
    _canonical_url = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-simple-observation"

    status: Optional[fhir.code] = Field(
        description="The status of the result value.",
        default=None,
    )
    category: Optional[List[Union[USCoreSimpleObservationProfileUsCore, CodeableConcept]]] = Field(
        description="(USCDI) Classification of  type of observation",
        default=None,
    )
    code: Optional[CodeableConcept] = Field(
        description="Describes what was observed. Sometimes this is called the observation \"name\".",
        default=None,
    )
    subject: Optional[Reference] = Field(
        description="The patient, or group of patients, location, or device this observation is about and into whose record the observation is placed. If the actual focus of the observation is different from the subject (or a sample of, part, or region of the subject), the `focus` element or the `code` itself specifies the actual focus of the observation.",
        default=None,
    )
    effectiveDateTime: Optional[fhir.dateTime] = Field(
        description="The time or time-period the observed value is asserted as being true. For biological subjects - e.g. human patients - this is usually called the \"physiologically relevant time\".",
        default=None,
    )
    effectivePeriod: Optional[Period] = Field(
        description="The time or time-period the observed value is asserted as being true. For biological subjects - e.g. human patients - this is usually called the \"physiologically relevant time\".",
        default=None,
    )
    effectiveTiming: Optional[Timing] = Field(
        description="The time or time-period the observed value is asserted as being true. For biological subjects - e.g. human patients - this is usually called the \"physiologically relevant time\".",
        default=None,
    )
    effectiveInstant: Optional[fhir.instant] = Field(
        description="The time or time-period the observed value is asserted as being true. For biological subjects - e.g. human patients - this is usually called the \"physiologically relevant time\".",
        default=None,
    )
    performer: Optional[List[Reference]] = Field(
        description="Who was responsible for asserting the observed value as \"true\".",
        default=None,
    )
    valueQuantity: Optional[Quantity] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueString: Optional[fhir.string] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueBoolean: Optional[fhir.boolean] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueInteger: Optional[fhir.integer] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueRange: Optional[Range] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueRatio: Optional[Ratio] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueSampledData: Optional[SampledData] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueTime: Optional[fhir.time_] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valueDateTime: Optional[fhir.dateTime] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    valuePeriod: Optional[Period] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    derivedFrom: Optional[List[Reference]] = Field(
        description="US Core Observations, DocumentReference, QuestionnaireResponse or other resource from which this observation value is derived.",
        default=None,
    )
    
    @property 
    def effective(self):
        return get_type_choice_value_by_base(self, 
            base="effective",
        )
        
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('category',), mode="after", check_fields=None)
    @classmethod
    def category_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="category",
        )
        
    @model_validator(mode="after")
    def effective_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['DateTime', 'Period', 'Timing', 'Instant'],
            field_name_base="effective",
            required=False,
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['Quantity', 'CodeableConcept', 'String', 'Boolean', 'Integer', 'Range', 'Ratio', 'SampledData', 'Time', 'DateTime', 'Period'],
            field_name_base="value",
            required=False,
        )
        
    @model_validator(mode="after")
    def FHIR_obs_6_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='dataAbsentReason.empty() or value.empty()',
            human='dataAbsentReason SHALL only be present if Observation.value[x] is not present',
            key='obs-6',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_obs_7_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='value.empty() or component.code.where(coding.intersect(%resource.code.coding).exists()).empty()',
            human='If Observation.code is the same as an Observation.component.code then the value element associated with the code SHALL NOT be present',
            key='obs-7',
            severity='error',
        )
        
 
class CancerStageComponent(ObservationComponent):
    """
    Some observations have multiple component observations.  These component observations are expressed as separate code value pairs that share the same attributes.  Examples include systolic and diastolic component observations for blood pressure measurement and multiple component observations for genetics observations.
    """


    code: Optional[CodeableConcept] = Field(
        description="Describes what was observed. Sometimes this is called the observation \"code\".",
        default=None,
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="The information determined as a result of making the observation, if the information has a simple value.",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=False,
        )
        
 
class CancerStage(USCoreSimpleObservationProfile):
    """
    assessment observation
    """

    _canonical_url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-cancer-stage"

    code: Optional[CodeableConcept] = Field(
        description="The kind of stage reported, e.g., a pathologic TNM stage, a Lugano lymphoma stage, or a Rai stage for leukemia. This element identifies the type of value that is reported in Observation.value and is necessary for the correct interpretation of that value. The distinction between Observation.code and Observation.method is important. Observation.code identifies the kind of stage being reported while Observation.method represents the staging system used to determine the code. Observation.code may imply the staging system. For example, the SNOMED CT 103420007 says the reported value is a modified Dukes stage, implying the Modified Dukes staging system (SNOMED CT 385359000) was used to determine the stage. When the staging system is implied by Observation.code, Observation.method is not required. However, when Observation.code does not imply a staging system (for example, if the code is SNOMED CT 385388004 Lymphoma stage), then the staging system must be specified in Observation.method. The value (Observation.valueCodeableConcept) may also imply certain things about the kind of stage being reported. For example, the value cN0 implies the value is a clinical stage. However, even if the value is partly or wholly self-identifying, it is not a reliable indicator of the type of stage being reported or the method of staging. Therefore, Observation.code must in all cases be reported.",
        default=None,
    )
    subject: Optional[Reference] = Field(
        description="The patient associated with staging assessment.",
        default=None,
    )
    focus: Optional[List[Reference]] = Field(
        description="Staging is associated with a particular primary cancer condition. Observation.focus is used to point back to that condition.",
        default=None,
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="The stage, stage group, category, or classification resulting from the staging evaluation.",
        default=None,
    )
    method: Optional[CodeableConcept] = Field(
        description="The staging system or protocol used to determine the stage, stage group, or category of the cancer based on its extent. When the staging system is implied by Observation.code, Observation.method is not required. However, when Observation.code does not imply a staging system (for example, if the code is SNOMED CT 385388004 Lymphoma stage), then the staging system must be specified in Observation.method. ",
        default=None,
    )
    device: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    referenceRange: Optional[List[ObservationReferenceRange]] = Field(
        description="Not used in this profile",
        default=None,
    )
    hasMember: Optional[List[Reference]] = Field(
        description="References to the prognostic factors affecting the stage, for example, the T, N, and M categories.",
        default=None,
    )
    component: Optional[List[CancerStageComponent]] = Field(
        description="Some observations have multiple component observations.  These component observations are expressed as separate code value pairs that share the same attributes.  Examples include systolic and diastolic component observations for blood pressure measurement and multiple component observations for genetics observations.",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=False,
        )
        
    @model_validator(mode="after")
    def FHIR_obs_3_constraint_validator(self):
        return validate_element_constraint( 
            self,
            elements="referenceRange",
            expression='low.exists() or high.exists() or text.exists()',
            human='Must have at least a low or a high or text',
            key='obs-3',
            severity='error',
        )
        
 
class LymphomaStageStageModifier(CancerStageComponent, FHIRSliceModel):
    """
    Some observations have multiple component observations.  These component observations are expressed as separate code value pairs that share the same attributes.  Examples include systolic and diastolic component observations for blood pressure measurement and multiple component observations for genetics observations.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None


    code: Optional[CodeableConcept] = Field(
        description="Describes what was observed. Sometimes this is called the observation \"code\".",
        default_factory=lambda: CodeableConcept(coding=[Coding(code='106252000', display='Staging classification for lymphoma (tumor staging)', system='http://snomed.info/sct')]),
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('code',), mode="after", check_fields=None)
    @classmethod
    def FHIR_code_pattern_constraint(cls, value):    
        return validate_FHIR_element_pattern(cls, value, 
            pattern=CodeableConcept(coding=[Coding(code='106252000', display='Staging classification for lymphoma (tumor staging)', system='http://snomed.info/sct')]),
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=False,
        )
        
 
class LymphomaStageClinOrPathModifier(CancerStageComponent, FHIRSliceModel):
    """
    Some observations have multiple component observations.  These component observations are expressed as separate code value pairs that share the same attributes.  Examples include systolic and diastolic component observations for blood pressure measurement and multiple component observations for genetics observations.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1


    code: Optional[CodeableConcept] = Field(
        description="Describes what was observed. Sometimes this is called the observation \"code\".",
        default_factory=lambda: CodeableConcept(coding=[Coding(code='277366005', display='Nature of staging values (qualifier value)', system='http://snomed.info/sct')]),
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('code',), mode="after", check_fields=None)
    @classmethod
    def FHIR_code_pattern_constraint(cls, value):    
        return validate_FHIR_element_pattern(cls, value, 
            pattern=CodeableConcept(coding=[Coding(code='277366005', display='Nature of staging values (qualifier value)', system='http://snomed.info/sct')]),
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=False,
        )
        
 
class LymphomaStageBulkyModifier(CancerStageComponent, FHIRSliceModel):
    """
    Some observations have multiple component observations.  These component observations are expressed as separate code value pairs that share the same attributes.  Examples include systolic and diastolic component observations for blood pressure measurement and multiple component observations for genetics observations.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1


    code: Optional[CodeableConcept] = Field(
        description="Describes what was observed. Sometimes this is called the observation \"code\".",
        default_factory=lambda: CodeableConcept(coding=[Coding(code='260873006', display='Bulky disease status (attribute)', system='http://snomed.info/sct')]),
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('code',), mode="after", check_fields=None)
    @classmethod
    def FHIR_code_pattern_constraint(cls, value):    
        return validate_FHIR_element_pattern(cls, value, 
            pattern=CodeableConcept(coding=[Coding(code='260873006', display='Bulky disease status (attribute)', system='http://snomed.info/sct')]),
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=False,
        )
        
 
class LymphomaStage(CancerStage):
    """
    assessment observation
    """

    _canonical_url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-lymphoma-stage"

    code: Optional[CodeableConcept] = Field(
        description="The kind of stage reported, e.g., a pathologic TNM stage, a Lugano lymphoma stage, or a Rai stage for leukemia. This element identifies the type of value that is reported in Observation.value and is necessary for the correct interpretation of that value. The distinction between Observation.code and Observation.method is important. Observation.code identifies the kind of stage being reported while Observation.method represents the staging system used to determine the code. Observation.code may imply the staging system. For example, the SNOMED CT 103420007 says the reported value is a modified Dukes stage, implying the Modified Dukes staging system (SNOMED CT 385359000) was used to determine the stage. When the staging system is implied by Observation.code, Observation.method is not required. However, when Observation.code does not imply a staging system (for example, if the code is SNOMED CT 385388004 Lymphoma stage), then the staging system must be specified in Observation.method. The value (Observation.valueCodeableConcept) may also imply certain things about the kind of stage being reported. For example, the value cN0 implies the value is a clinical stage. However, even if the value is partly or wholly self-identifying, it is not a reliable indicator of the type of stage being reported or the method of staging. Therefore, Observation.code must in all cases be reported.",
        default_factory=lambda: CodeableConcept(coding=[Coding(code='385388004', system='http://snomed.info/sct')]),
    )
    component: Optional[List[Union[LymphomaStageStageModifier, LymphomaStageClinOrPathModifier, LymphomaStageBulkyModifier, CancerStageComponent]]] = Field(
        description="Component results",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('code',), mode="after", check_fields=None)
    @classmethod
    def FHIR_code_pattern_constraint(cls, value):    
        return validate_FHIR_element_pattern(cls, value, 
            pattern=CodeableConcept(coding=[Coding(code='385388004', system='http://snomed.info/sct')]),
        )
        
    @field_validator(*('component',), mode="after", check_fields=None)
    @classmethod
    def component_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="component",
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=False,
        )
        
 
class OnconovaLymphomaStage(LymphomaStage):
    """
    assessment observation
    """

    _canonical_url = "http://onconova.github.io/fhir/StructureDefinition/onconova-lymphoma-stage"

    status: Optional[fhir.code] = Field(
        description="Not used in this profile",
        default=None,
    )
    focus: Optional[List[Reference]] = Field(
        description="Staging is associated with a particular primary cancer condition. Observation.focus is used to point back to that condition.",
        default=None,
    )
    encounter: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    issued: Optional[fhir.instant] = Field(
        description="Not used in this profile",
        default=None,
    )
    performer: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    interpretation: Optional[List[CodeableConcept]] = Field(
        description="Not used in this profile",
        default=None,
    )
    bodySite: Optional[CodeableConcept] = Field(
        description="Not used in this profile",
        default=None,
    )
    specimen: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    
    @property 
    def effective(self):
        return get_type_choice_value_by_base(self, 
            base="effective",
        )
        
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @model_validator(mode="after")
    def effective_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['DateTime'],
            field_name_base="effective",
            required=True,
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=True,
        )
        
    @model_validator(mode="after")
    def FHIR_o_stg_req_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='subject.exists()',
            human='The subject element is required and must be provided.',
            key='o-stg-req-1',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_o_stg_req_2_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='effectiveDateTime.exists() and effectiveDateTime.hasValue()',
            human='The effectiveDateTime element is required and must be provided.',
            key='o-stg-req-2',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_o_stg_req_3_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='valueCodeableConcept.exists() and valueCodeableConcept.coding.exists()',
            human='The valueCodeableConcept element is required and must be provided.',
            key='o-stg-req-3',
            severity='error',
        )
        
