# Code autogenerated by Fhircraft 0.5.0 on 2026-04-15 15:32:50.454199.
# pyright: reportIncompatibleVariableOverride=false

from fhircraft.fhir.resources.datatypes.R4.core.condition import Condition, ConditionEvidence, ConditionStage
from typing import Annotated, ClassVar, List, Optional, Union
from fhircraft.fhir.resources.datatypes.R4.complex import Address, Age, Annotation, Attachment, CodeableConcept, Coding, ContactDetail, ContactPoint, Contributor, Count, DataRequirement, Distance, Dosage, Duration, Expression, Extension, HumanName, Identifier, Meta, Money, ParameterDefinition, Period, Quantity, Range, Ratio, Reference, RelatedArtifact, SampledData, Signature, Timing, TriggerDefinition, UsageContext
from pydantic import Field, field_validator, model_validator
from fhircraft.fhir.resources.validators import get_type_choice_value_by_base, validate_FHIR_element_fixed_value, validate_FHIR_element_pattern, validate_element_constraint, validate_model_constraint, validate_slicing_cardinalities, validate_type_choice_element
from fhircraft.fhir.resources.datatypes.R4.primitive import Base64Binary, Boolean, Canonical, Code, Date, DateTime, Decimal, Id, Instant, Integer, Markdown, Oid, PositiveInt, String, Time, UnsignedInt, Uri, Url, Uuid
from fhircraft.fhir.resources.base import FHIRSliceModel, FhirBaseModelKind
import fhircraft.fhir.resources.datatypes.R4.primitive as fhir
NoneType = type(None)

 
class AssertedDate(Extension):
    """
    The date on which the existence of the Condition was first asserted or acknowledged.
    """

    _abstract = True
    _canonical_url = "http://hl7.org/fhir/StructureDefinition/condition-assertedDate"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: 'http://hl7.org/fhir/StructureDefinition/condition-assertedDate',
    )
    valueDateTime: Optional[fhir.dateTime] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @field_validator(*('url',), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):    
        return validate_FHIR_element_fixed_value(cls, value, 
            constant='http://hl7.org/fhir/StructureDefinition/condition-assertedDate',
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['DateTime'],
            field_name_base="value",
            required=True,
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class USCoreConditionProblemsHealthConcernsProfileAssertedDate(AssertedDate, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1


    pass
    
    @model_validator(mode="after")
    def FHIR_ele_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='hasValue() or (children().count() > id.count())',
            human='All FHIR elements must have a @value or children',
            key='ele-1',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class USCoreConditionProblemsHealthConcernsProfileUsCore(CodeableConcept, FHIRSliceModel):
    """
    A category assigned to the condition.
    """
    min_cardinality: ClassVar[int] = 1
    max_cardinality: ClassVar[int | None] = None


    pass
    
 
class USCoreConditionProblemsHealthConcernsProfileScreeningAssessment(CodeableConcept, FHIRSliceModel):
    """
    Categories that a provider may use in their workflow to classify that this Condition is related to a USCDI Health Status/Assessments Data Class.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None


    pass
    
 
class USCoreConditionProblemsHealthConcernsProfile(Condition):
    """
    Detailed information about conditions, problems or diagnoses
    """

    _abstract = True
    _canonical_url = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition-problems-health-concerns"

    extension: Optional[List[Union[USCoreConditionProblemsHealthConcernsProfileAssertedDate, Extension]]] = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    clinicalStatus: Optional[CodeableConcept] = Field(
        description="The clinical status of the condition.",
        default=None,
    )
    verificationStatus: Optional[CodeableConcept] = Field(
        description="The verification status to support the clinical status of the condition.",
        default=None,
    )
    category: Optional[List[Union[USCoreConditionProblemsHealthConcernsProfileUsCore, USCoreConditionProblemsHealthConcernsProfileScreeningAssessment, CodeableConcept]]] = Field(
        description="(USCDI) category codes",
        default=None,
    )
    code: Optional[CodeableConcept] = Field(
        description="Identification of the condition, problem or diagnosis.",
        default=None,
    )
    subject: Optional[Reference] = Field(
        description="Indicates the patient or group who the condition record is associated with.",
        default=None,
    )
    onsetDateTime: Optional[fhir.dateTime] = Field(
        description="Estimated or actual date or date-time  the condition began, in the opinion of the clinician.",
        default=None,
    )
    onsetAge: Optional[Age] = Field(
        description="Estimated or actual date or date-time  the condition began, in the opinion of the clinician.",
        default=None,
    )
    onsetPeriod: Optional[Period] = Field(
        description="Estimated or actual date or date-time  the condition began, in the opinion of the clinician.",
        default=None,
    )
    onsetRange: Optional[Range] = Field(
        description="Estimated or actual date or date-time  the condition began, in the opinion of the clinician.",
        default=None,
    )
    onsetString: Optional[fhir.string] = Field(
        description="Estimated or actual date or date-time  the condition began, in the opinion of the clinician.",
        default=None,
    )
    abatementDateTime: Optional[fhir.dateTime] = Field(
        description="The date or estimated date that the condition resolved or went into remission. This is called \"abatement\" because of the many overloaded connotations associated with \"remission\" or \"resolution\" - Conditions are never really resolved, but they can abate.",
        default=None,
    )
    abatementAge: Optional[Age] = Field(
        description="The date or estimated date that the condition resolved or went into remission. This is called \"abatement\" because of the many overloaded connotations associated with \"remission\" or \"resolution\" - Conditions are never really resolved, but they can abate.",
        default=None,
    )
    abatementPeriod: Optional[Period] = Field(
        description="The date or estimated date that the condition resolved or went into remission. This is called \"abatement\" because of the many overloaded connotations associated with \"remission\" or \"resolution\" - Conditions are never really resolved, but they can abate.",
        default=None,
    )
    abatementRange: Optional[Range] = Field(
        description="The date or estimated date that the condition resolved or went into remission. This is called \"abatement\" because of the many overloaded connotations associated with \"remission\" or \"resolution\" - Conditions are never really resolved, but they can abate.",
        default=None,
    )
    abatementString: Optional[fhir.string] = Field(
        description="The date or estimated date that the condition resolved or went into remission. This is called \"abatement\" because of the many overloaded connotations associated with \"remission\" or \"resolution\" - Conditions are never really resolved, but they can abate.",
        default=None,
    )
    recordedDate: Optional[fhir.dateTime] = Field(
        description="The recordedDate represents when this particular Condition record was created in the system, which is often a system-generated date.",
        default=None,
    )
    
    @property 
    def onset(self):
        return get_type_choice_value_by_base(self, 
            base="onset",
        )
        
    @property 
    def abatement(self):
        return get_type_choice_value_by_base(self, 
            base="abatement",
        )
        
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @field_validator(*('category',), mode="after", check_fields=None)
    @classmethod
    def category_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="category",
        )
        
    @model_validator(mode="after")
    def onset_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['DateTime', 'Age', 'Period', 'Range', 'String'],
            field_name_base="onset",
            required=False,
        )
        
    @model_validator(mode="after")
    def abatement_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['DateTime', 'Age', 'Period', 'Range', 'String'],
            field_name_base="abatement",
            required=False,
        )
        
    @model_validator(mode="after")
    def FHIR_con_3_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression="clinicalStatus.exists() or verificationStatus.coding.where(system='http://terminology.hl7.org/CodeSystem/condition-ver-status' and code = 'entered-in-error').exists() or category.select($this='problem-list-item').empty()",
            human='Condition.clinicalStatus SHALL be present if verificationStatus is not entered-in-error and category is problem-list-item',
            key='con-3',
            severity='warning',
        )
        
    @model_validator(mode="after")
    def FHIR_con_4_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression="abatement.empty() or clinicalStatus.coding.where(system='http://terminology.hl7.org/CodeSystem/condition-clinical' and (code='resolved' or code='remission' or code='inactive')).exists()",
            human='If condition is abated, then clinicalStatus must be either inactive, resolved, or remission',
            key='con-4',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_con_5_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression="verificationStatus.coding.where(system='http://terminology.hl7.org/CodeSystem/condition-ver-status' and code='entered-in-error').empty() or clinicalStatus.empty()",
            human='Condition.clinicalStatus SHALL NOT be present if verification Status is entered-in-error',
            key='con-5',
            severity='error',
        )
        
 
class HistologyMorphologyBehavior(Extension):
    """
    An extension describing the morphologic and behavioral characteristics of the cancer.
    """

    _abstract = True
    _canonical_url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-histology-morphology-behavior"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: 'http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-histology-morphology-behavior',
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @field_validator(*('url',), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):    
        return validate_FHIR_element_fixed_value(cls, value, 
            constant='http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-histology-morphology-behavior',
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=True,
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class PrimaryCancerConditionHistologyMorphologyBehavior(HistologyMorphologyBehavior, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1


    pass
    
 
class BodyLocationQualifier(Extension):
    """
    Qualifier to refine an body location. These include qualifiers for relative location, directionality, number, and plane, and exclude qualifiers for laterality.
    """

    _abstract = True
    _canonical_url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-body-location-qualifier"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: 'http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-body-location-qualifier',
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @field_validator(*('url',), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):    
        return validate_FHIR_element_fixed_value(cls, value, 
            constant='http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-body-location-qualifier',
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=True,
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class PrimaryCancerConditionLocationQualifier(BodyLocationQualifier, FHIRSliceModel):
    """
    General location qualifier (excluding laterality) for this bodySite
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None


    pass
    
 
class LateralityQualifier(Extension):
    """
    Qualifier to specify laterality.
    """

    _abstract = True
    _canonical_url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-laterality-qualifier"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: 'http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-laterality-qualifier',
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @field_validator(*('url',), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):    
        return validate_FHIR_element_fixed_value(cls, value, 
            constant='http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-laterality-qualifier',
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=True,
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class PrimaryCancerConditionLateralityQualifier(LateralityQualifier, FHIRSliceModel):
    """
    Laterality qualifier for this bodySite
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1


    pass
    
 
class PrimaryCancerConditionBodySite(CodeableConcept):
    """
    The anatomical location where this condition manifests itself.
    """


    extension: Optional[List[Union[USCoreConditionProblemsHealthConcernsProfileAssertedDate, PrimaryCancerConditionLocationQualifier, PrimaryCancerConditionLateralityQualifier, Extension]]] = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
 
class PrimaryCancerConditionStage(ConditionStage):
    """
    Clinical stage or grade of a condition. May include formal severity assessments.
    """


    summary: Optional[CodeableConcept] = Field(
        description="Most recent overall cancer stage, such as stage group IIA in TNM staging. More detailed staging information (such as the individual T, N, and M categories) SHOULD be captured in a separate Observation resource, referenced by stage.assessment, conforming to CancerStage profile.",
        default=None,
    )
    assessment: Optional[List[Reference]] = Field(
        description="Reference to a formal record of the evidence on which the staging assessment is based.",
        default=None,
    )
    type: Optional[CodeableConcept] = Field(
        description="The type of stage reported in stage.summary, or the staging method used to arrive at the stage.summary value.",
        default=None,
    )
    
    @model_validator(mode="after")
    def FHIR_con_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='summary.exists() or assessment.exists()',
            human='Stage SHALL have summary or assessment',
            key='con-1',
            severity='error',
        )
        
 
class PrimaryCancerConditionEvidence(ConditionEvidence):
    """
    Supporting evidence / manifestations that are the basis of the Condition's verification status, such as evidence that confirmed or refuted the condition.
    """


    code: Optional[List[CodeableConcept]] = Field(
        description="A manifestation or symptom that led to the recording of this condition.",
        default=None,
    )
    
 
class PrimaryCancerCondition(USCoreConditionProblemsHealthConcernsProfile):
    """
    Detailed information about conditions, problems or diagnoses
    """

    _canonical_url = "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-primary-cancer-condition"

    extension: Optional[List[Union[USCoreConditionProblemsHealthConcernsProfileAssertedDate, PrimaryCancerConditionHistologyMorphologyBehavior, Extension]]] = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    bodySite: Optional[List[PrimaryCancerConditionBodySite]] = Field(
        description="The anatomical location where this condition manifests itself.",
        default=None,
    )
    stage: Optional[List[PrimaryCancerConditionStage]] = Field(
        description="Clinical stage or grade of a condition. May include formal severity assessments.",
        default=None,
    )
    evidence: Optional[List[PrimaryCancerConditionEvidence]] = Field(
        description="Supporting evidence / manifestations that are the basis of the Condition\u0027s verification status, such as evidence that confirmed or refuted the condition.",
        default=None,
    )
    
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @model_validator(mode="after")
    def FHIR_con_1_constraint_validator(self):
        return validate_element_constraint( 
            self,
            elements="stage",
            expression='summary.exists() or assessment.exists()',
            human='Stage SHALL have summary or assessment',
            key='con-1',
            severity='error',
        )
        
 
class OnconovaPrimaryCancerConditionAssertedDate(Extension, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None


    pass
    
 
class OnconovaPrimaryCancerConditionHistologyMorphologyBehavior(Extension, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """
    min_cardinality: ClassVar[int] = 1
    max_cardinality: ClassVar[int | None] = None


    valueBase64Binary: Optional[fhir.base64Binary] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueBoolean: Optional[fhir.boolean] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueCanonical: Optional[fhir.canonical] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueCode: Optional[fhir.code] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDate: Optional[fhir.date_] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDateTime: Optional[fhir.dateTime] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDecimal: Optional[fhir.decimal] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueId: Optional[fhir.id_] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueInstant: Optional[fhir.instant] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueInteger: Optional[fhir.integer] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueMarkdown: Optional[fhir.markdown] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueOid: Optional[fhir.oid] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valuePositiveInt: Optional[fhir.positiveInt] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueString: Optional[fhir.string] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueTime: Optional[fhir.time_] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueUnsignedInt: Optional[fhir.unsignedInt] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueUri: Optional[fhir.uri] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueUrl: Optional[fhir.url] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueUuid: Optional[fhir.uuid] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueAddress: Optional[Address] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueAge: Optional[Age] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueAnnotation: Optional[Annotation] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueAttachment: Optional[Attachment] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueCoding: Optional[Coding] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueContactPoint: Optional[ContactPoint] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueCount: Optional[Count] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDistance: Optional[Distance] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDuration: Optional[Duration] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueHumanName: Optional[HumanName] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueIdentifier: Optional[Identifier] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueMoney: Optional[Money] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valuePeriod: Optional[Period] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueQuantity: Optional[Quantity] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueRange: Optional[Range] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueRatio: Optional[Ratio] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueReference: Optional[Reference] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueSampledData: Optional[SampledData] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueSignature: Optional[Signature] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueTiming: Optional[Timing] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueContactDetail: Optional[ContactDetail] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueContributor: Optional[Contributor] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDataRequirement: Optional[DataRequirement] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueExpression: Optional[Expression] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueParameterDefinition: Optional[ParameterDefinition] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueRelatedArtifact: Optional[RelatedArtifact] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueTriggerDefinition: Optional[TriggerDefinition] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueUsageContext: Optional[UsageContext] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueDosage: Optional[Dosage] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    valueMeta: Optional[Meta] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['Base64Binary', 'Boolean', 'Canonical', 'Code', 'Date', 'DateTime', 'Decimal', 'Id', 'Instant', 'Integer', 'Markdown', 'Oid', 'PositiveInt', 'String', 'Time', 'UnsignedInt', 'Uri', 'Url', 'Uuid', 'Address', 'Age', 'Annotation', 'Attachment', 'CodeableConcept', 'Coding', 'ContactPoint', 'Count', 'Distance', 'Duration', 'HumanName', 'Identifier', 'Money', 'Period', 'Quantity', 'Range', 'Ratio', 'Reference', 'SampledData', 'Signature', 'Timing', 'ContactDetail', 'Contributor', 'DataRequirement', 'Expression', 'ParameterDefinition', 'RelatedArtifact', 'TriggerDefinition', 'UsageContext', 'Dosage', 'Meta'],
            field_name_base="value",
            required=False,
        )
        
 
class HistologicalDifferentiation(Extension):
    """
    The histological differentiation of the tumor.
    """

    _abstract = True
    _canonical_url = "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-histological-differentiation"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: 'http://onconova.github.io/fhir/StructureDefinition/onconova-ext-histological-differentiation',
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @field_validator(*('url',), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):    
        return validate_FHIR_element_fixed_value(cls, value, 
            constant='http://onconova.github.io/fhir/StructureDefinition/onconova-ext-histological-differentiation',
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=False,
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class OnconovaPrimaryCancerConditionDifferentiation(HistologicalDifferentiation, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1


    pass
    
 
class PrimaryCancerRecurrenceType(Extension):
    """
    Indicates the type of recurrence for the condition (local or regional).
    """

    _abstract = True
    _canonical_url = "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-primary-cancer-recurrence-type"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: 'http://onconova.github.io/fhir/StructureDefinition/onconova-ext-primary-cancer-recurrence-type',
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @field_validator(*('url',), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):    
        return validate_FHIR_element_fixed_value(cls, value, 
            constant='http://onconova.github.io/fhir/StructureDefinition/onconova-ext-primary-cancer-recurrence-type',
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['CodeableConcept'],
            field_name_base="value",
            required=False,
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class OnconovaPrimaryCancerConditionRecurrenceType(PrimaryCancerRecurrenceType, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1


    pass
    
 
class PrimaryCancerRecurrenceOf(Extension):
    """
    Indicates that the condition is a recurrence of a previous condition, and provides a reference to that previous condition.
    """

    _abstract = True
    _canonical_url = "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-primary-cancer-recurrence-of"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: 'http://onconova.github.io/fhir/StructureDefinition/onconova-ext-primary-cancer-recurrence-of',
    )
    valueReference: Optional[Reference] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )
    
    @property 
    def value(self):
        return get_type_choice_value_by_base(self, 
            base="value",
        )
        
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @field_validator(*('url',), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):    
        return validate_FHIR_element_fixed_value(cls, value, 
            constant='http://onconova.github.io/fhir/StructureDefinition/onconova-ext-primary-cancer-recurrence-of',
        )
        
    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element( 
            self,
            field_types=['Reference'],
            field_name_base="value",
            required=False,
        )
        
    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='extension.exists() != value.exists()',
            human='Must have either extensions or value[x], not both',
            key='ext-1',
            severity='error',
        )
        
 
class OnconovaPrimaryCancerConditionRecurrenceOf(PrimaryCancerRecurrenceOf, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1


    pass
    
 
class OnconovaPrimaryCancerConditionClinicalStatus(CodeableConcept):
    """
    The clinical status of the condition.
    """


    extension: Optional[List[Union[USCoreConditionProblemsHealthConcernsProfileAssertedDate, PrimaryCancerConditionHistologyMorphologyBehavior, OnconovaPrimaryCancerConditionRecurrenceType, OnconovaPrimaryCancerConditionRecurrenceOf, Extension]]] = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
 
class OnconovaPrimaryCancerConditionLocationQualifier(Extension, FHIRSliceModel):
    """
    Not used in this profile
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None


    pass
    
 
class OnconovaPrimaryCancerConditionLateralityQualifier(Extension, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """
    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None


    pass
    
 
class OnconovaPrimaryCancerConditionBodySite(PrimaryCancerConditionBodySite):
    """
    The anatomical location where this condition manifests itself.
    """


    extension: Optional[List[Union[USCoreConditionProblemsHealthConcernsProfileAssertedDate, PrimaryCancerConditionHistologyMorphologyBehavior, OnconovaPrimaryCancerConditionLocationQualifier, OnconovaPrimaryCancerConditionLateralityQualifier, Extension]]] = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
 
class OnconovaPrimaryCancerCondition(PrimaryCancerCondition):
    """
    Detailed information about conditions, problems or diagnoses
    """

    _canonical_url = "http://onconova.github.io/fhir/StructureDefinition/onconova-primary-cancer-condition"

    extension: Optional[List[Union[USCoreConditionProblemsHealthConcernsProfileAssertedDate, PrimaryCancerConditionHistologyMorphologyBehavior, OnconovaPrimaryCancerConditionAssertedDate, OnconovaPrimaryCancerConditionHistologyMorphologyBehavior, OnconovaPrimaryCancerConditionDifferentiation, Extension]]] = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    clinicalStatus: Optional[OnconovaPrimaryCancerConditionClinicalStatus] = Field(
        description="The clinical status of the condition.",
        default=None,
    )
    verificationStatus: Optional[CodeableConcept] = Field(
        description="Not used in this profile",
        default=None,
    )
    severity: Optional[CodeableConcept] = Field(
        description="Not used in this profile",
        default=None,
    )
    code: Optional[CodeableConcept] = Field(
        description="Identification of the condition, problem or diagnosis.",
        default_factory=lambda: CodeableConcept(coding=[Coding(code='363346000', display='Malignant neoplastic disease', system='http://snomed.info/sct')]),
    )
    bodySite: Optional[List[OnconovaPrimaryCancerConditionBodySite]] = Field(
        description="The anatomical location where this condition manifests itself.",
        default=None,
    )
    encounter: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    recordedDate: Optional[fhir.dateTime] = Field(
        description="Not used in this profile",
        default=None,
    )
    recorder: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    asserter: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    stage: Optional[List[PrimaryCancerConditionStage]] = Field(
        description="Not used in this profile",
        default=None,
    )
    evidence: Optional[List[PrimaryCancerConditionEvidence]] = Field(
        description="Not used in this profile",
        default=None,
    )
    
    @field_validator(*('extension',), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):    
        return validate_slicing_cardinalities(cls, value, 
            field_name="extension",
        )
        
    @field_validator(*('code',), mode="after", check_fields=None)
    @classmethod
    def FHIR_code_pattern_constraint(cls, value):    
        return validate_FHIR_element_pattern(cls, value, 
            pattern=CodeableConcept(coding=[Coding(code='363346000', display='Malignant neoplastic disease', system='http://snomed.info/sct')]),
        )
        
    @model_validator(mode="after")
    def FHIR_con_1_constraint_validator(self):
        return validate_element_constraint( 
            self,
            elements="stage",
            expression='summary.exists() or assessment.exists()',
            human='Stage SHALL have summary or assessment',
            key='con-1',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_o_con_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression="clinicalStatus.exists() and clinicalStatus.coding.code = 'recurrence' implies extension('http://onconova.github.io/fhir/StructureDefinition/onconova-ext-recurrence-of').exists()",
            human="If clinicalStatus is 'recurrence', the recurrenceOf extension must be provided.",
            key='o-con-1',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_o_con_2_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression="clinicalStatus.exists() and clinicalStatus.coding.code = 'recurrence' implies clinicalStatus.extension('http://onconova.github.io/fhir/StructureDefinition/onconova-ext-recurrence-type').exists()",
            human="If clinicalStatus is 'recurrence', the type of recurrence must be provided.",
            key='o-con-2',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_o_con_req_1_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='subject.exists()',
            human='The subject element is required and must be provided.',
            key='o-con-req-1',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_o_con_req_2_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression="extension('http://hl7.org/fhir/StructureDefinition/condition-assertedDate').exists()",
            human='The assertedDate extension is required and must be provided.',
            key='o-con-req-2',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_o_con_req_3_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression='bodySite.exists() and bodySite.coding.exists()',
            human='The bodySite element is required and must be provided.',
            key='o-con-req-3',
            severity='error',
        )
        
    @model_validator(mode="after")
    def FHIR_o_con_req_4_constraint_validator(self):
        return validate_model_constraint( 
            self,
            expression="extension('http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-histology-morphology-behavior').exists()",
            human='The histologyMorphologyBehavior extension is required and must be provided.',
            key='o-con-req-4',
            severity='error',
        )
        
