# Code autogenerated by Fhircraft 0.5.0 on 2026-04-15 15:32:50.154550.
# pyright: reportIncompatibleVariableOverride=false

from fhircraft.fhir.resources.datatypes.R4.core.episode_of_care import (
    EpisodeOfCare,
    EpisodeOfCareDiagnosis,
    EpisodeOfCareStatusHistory,
)
from typing import Annotated, ClassVar, List, Optional, Union
from fhircraft.fhir.resources.datatypes.R4.complex import (
    CodeableConcept,
    Coding,
    Duration,
    Extension,
    Period,
    Reference,
)
from pydantic import Field, field_validator, model_validator
from fhircraft.fhir.resources.validators import (
    get_type_choice_value_by_base,
    validate_FHIR_element_fixed_value,
    validate_FHIR_element_pattern,
    validate_model_constraint,
    validate_slicing_cardinalities,
    validate_type_choice_element,
)
from fhircraft.fhir.resources.datatypes.R4.primitive import Date, PositiveInt
from fhircraft.fhir.resources.base import FHIRSliceModel, FhirBaseModelKind
import fhircraft.fhir.resources.datatypes.R4.primitive as fhir

NoneType = type(None)


class TherapyLineNumber(Extension):
    """
    The number representing the sequence of the therapy line in the overall treatment regimen.
    """

    _abstract = True
    _canonical_url = "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-number"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-number",
    )
    valuePositiveInt: Optional[fhir.positiveInt] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="extension",
        )

    @field_validator(*("url",), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):
        return validate_FHIR_element_fixed_value(
            cls,
            value,
            constant="http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-number",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=["PositiveInt"],
            field_name_base="value",
            required=False,
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )


class OnconovaTherapyLineTherapyLineNumber(TherapyLineNumber, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1

    pass

    @model_validator(mode="after")
    def FHIR_ele_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )


class TherapyLineIntent(Extension):
    """
    The intent of the therapy line, such as curative or palliative.
    """

    _abstract = True
    _canonical_url = "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-intent"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-intent",
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="extension",
        )

    @field_validator(*("url",), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):
        return validate_FHIR_element_fixed_value(
            cls,
            value,
            constant="http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-intent",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=["CodeableConcept"],
            field_name_base="value",
            required=False,
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )


class OnconovaTherapyLineTherapyLineIntent(TherapyLineIntent, FHIRSliceModel):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1

    pass

    @model_validator(mode="after")
    def FHIR_ele_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )


class TherapyLineProgressionFreeSurvival(Extension):
    """
    The progression-free survival duration for the therapy line.
    """

    _abstract = True
    _canonical_url = "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-progression-free-survival"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-progression-free-survival",
    )
    valueDuration: Optional[Duration] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="extension",
        )

    @field_validator(*("url",), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):
        return validate_FHIR_element_fixed_value(
            cls,
            value,
            constant="http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-progression-free-survival",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=["Duration"],
            field_name_base="value",
            required=False,
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )


class OnconovaTherapyLineTherapyLineProgressionFreeSurvival(
    TherapyLineProgressionFreeSurvival, FHIRSliceModel
):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1

    pass

    @model_validator(mode="after")
    def FHIR_ele_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )


class TherapyLineProgressionDate(Extension):
    """
    The date when disease progression was observed during or after the therapy line.
    """

    _abstract = True
    _canonical_url = "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-progression-date"

    extension: None = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    url: Optional[str] = Field(
        description="Source of the definition for the extension code - a logical name or a URL.",
        default_factory=lambda: "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-progression-date",
    )
    valueDate: Optional[fhir.date_] = Field(
        description="Value of extension - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list).",
        default=None,
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="extension",
        )

    @field_validator(*("url",), mode="after", check_fields=None)
    @classmethod
    def FHIR_url_fixed_value_constraint(cls, value):
        return validate_FHIR_element_fixed_value(
            cls,
            value,
            constant="http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-progression-date",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=["Date"],
            field_name_base="value",
            required=False,
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )


class OnconovaTherapyLineTherapyLineProgressionDate(
    TherapyLineProgressionDate, FHIRSliceModel
):
    """
    May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1

    pass

    @model_validator(mode="after")
    def FHIR_ele_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )


class OnconovaTherapyLine(EpisodeOfCare):
    """
    An association between a patient and an organization / healthcare provider(s) during which time encounters may occur. The managing organization assumes a level of responsibility for the patient during this time.
    """

    _abstract = True
    _canonical_url = (
        "http://onconova.github.io/fhir/StructureDefinition/onconova-therapy-line"
    )

    extension: Optional[
        List[
            Union[
                OnconovaTherapyLineTherapyLineNumber,
                OnconovaTherapyLineTherapyLineIntent,
                OnconovaTherapyLineTherapyLineProgressionFreeSurvival,
                OnconovaTherapyLineTherapyLineProgressionDate,
                Extension,
            ]
        ]
    ] = Field(
        description="Additional content defined by implementations",
        default=None,
    )
    status: Optional[fhir.code] = Field(
        description="Not used in this profile",
        default=None,
    )
    statusHistory: Optional[List[EpisodeOfCareStatusHistory]] = Field(
        description="Not used in this profile",
        default=None,
    )
    type: Optional[List[CodeableConcept]] = Field(
        description="A classification of the type of episode of care; e.g. specialist referral, disease management, type of funded care.",
        default=[
            CodeableConcept(
                coding=[
                    Coding(
                        code="C133518",
                        display="Line of Therapy",
                        system="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl",
                    )
                ]
            )
        ],
    )
    diagnosis: Optional[List[EpisodeOfCareDiagnosis]] = Field(
        description="Not used in this profile",
        default=None,
    )
    patient: Optional[Reference] = Field(
        description="The patient who is the focus of this episode of care.",
        default=None,
    )
    managingOrganization: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    period: Optional[Period] = Field(
        description="The interval during which the managing organization assumes the defined responsibility.",
        default=None,
    )
    referralRequest: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    careManager: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    team: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    account: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="extension",
        )

    @field_validator(*("type",), mode="after", check_fields=None)
    @classmethod
    def FHIR_type_pattern_constraint(cls, value):
        return validate_FHIR_element_pattern(
            cls,
            value,
            pattern=CodeableConcept(
                coding=[
                    Coding(
                        code="C133518",
                        display="Line of Therapy",
                        system="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl",
                    )
                ]
            ),
        )

    @model_validator(mode="after")
    def FHIR_o_lin_req_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="patient.exists()",
            human="The patient element is required and must be provided.",
            key="o-lin-req-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_o_lin_req_3_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="extension('http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-number').exists()",
            human="The therapyLineNumber extension is required and must be provided.",
            key="o-lin-req-3",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_o_lin_req_4_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="extension('http://onconova.github.io/fhir/StructureDefinition/onconova-ext-therapy-line-intent').exists()",
            human="The therapyLineIntent extension is required and must be provided.",
            key="o-lin-req-4",
            severity="error",
        )
