# Code autogenerated by Fhircraft 0.4.1 on 2025-12-04 08:15:10.211806.

# Fhircraft modules
from fhircraft.fhir.resources.base import FHIRBaseModel, FHIRSliceModel
import fhircraft.fhir.resources.validators as fhir_validators

# Pydantic modules
from pydantic import Field, field_validator, model_validator, BaseModel
from pydantic.fields import FieldInfo

# Standard modules
from typing import Optional, Literal, Union, ClassVar
from enum import Enum

NoneType = type(None)

# Dynamic modules
from fhircraft.fhir.resources.base import FHIRBaseModel, FHIRSliceModel
from typing import Annotated, List, Literal, Optional, Union
from fhircraft.fhir.resources.datatypes.primitives import (
    Boolean,
    Code,
    DateTime,
    Instant,
    Integer,
    String,
    Time,
    Uri,
)
from fhircraft.fhir.resources.datatypes.R4.complex import (
    DomainResource,
    Annotation,
    BackboneElement,
    CodeableConcept,
    Element,
    Extension,
    Identifier,
    Meta,
    Narrative,
    Period,
    Quantity,
    Range,
    Ratio,
    Reference,
    Resource,
    SampledData,
)
from fhircraft.fhir.resources.validators import (
    get_type_choice_value_by_base,
    validate_element_constraint,
    validate_model_constraint,
    validate_slicing_cardinalities,
    validate_type_choice_element,
)


class RelatedCondition(FHIRSliceModel):
    """
    A condition that has a relationship with the resource.
    """

    min_cardinality: ClassVar[int] = 1
    max_cardinality: ClassVar[int] = 99999
    id: Optional[String] = Field(
        description="Unique id for inter-element referencing",
        default=None,
    )
    id_ext: Optional[Element] = Field(
        description="Placeholder element for id extensions",
        default=None,
        alias="_id",
    )
    extension: Optional[Extension] = Field(
        description="Extension",
        default=None,
    )
    url: Literal[
        "http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition"
    ] = Field(
        description="identifies the meaning of the extension",
        default="http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-related-condition",
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension",
        default=None,
    )
    valueReference: Optional[Reference] = Field(
        description="Value of extension",
        default=None,
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[CodeableConcept, Reference],
            field_name_base="value",
            required=True,
        )

    @model_validator(mode="after")
    def FHIR_ele_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )


class OnconovaTumorMarkerUsCore(CodeableConcept, FHIRSliceModel):
    """
    (USCDI) Classification of  type of observation
    """

    min_cardinality: ClassVar[int] = 1
    max_cardinality: ClassVar[int] = 1
    pass


class TumorMarkerAnalyte(FHIRSliceModel):
    """
    The specific analyte or substance being measured as a tumor marker, such as PSA, CA-125, or CEA.
    """

    min_cardinality: ClassVar[int] = 1
    max_cardinality: ClassVar[int] = 1
    id: Optional[String] = Field(
        description="Unique id for inter-element referencing",
        default=None,
    )
    id_ext: Optional[Element] = Field(
        description="Placeholder element for id extensions",
        default=None,
        alias="_id",
    )
    extension: Optional[Extension] = Field(
        description="Extension",
        default=None,
    )
    url: Literal[
        "http://onconova.github.io/fhir/StructureDefinition/onconova-ext-tumor-marker-analyte"
    ] = Field(
        description="identifies the meaning of the extension",
        default="http://onconova.github.io/fhir/StructureDefinition/onconova-ext-tumor-marker-analyte",
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Value of extension",
        default=None,
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[CodeableConcept],
            field_name_base="value",
            required=False,
        )

    @model_validator(mode="after")
    def FHIR_ele_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_ext_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )


class OnconovaTumorMarkerCode(CodeableConcept):
    """
    The name of the clinical test or procedure performed on a patient.  A LOINC **SHALL** be used if the concept is present in LOINC.
    """

    extension: Optional[
        List[
            Annotated[
                Union[TumorMarkerAnalyte, Extension], Field(union_mode="left_to_right")
            ]
        ]
    ] = Field(
        description=None,
        default=None,
    )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="extension",
        )


class OnconovaTumorMarkerReferenceRange(BackboneElement):
    """
    Not used in this profile
    """

    low: Optional[Quantity] = Field(
        description="Low Range, if relevant",
        default=None,
    )
    high: Optional[Quantity] = Field(
        description="High Range, if relevant",
        default=None,
    )
    type: Optional[CodeableConcept] = Field(
        description="Reference range qualifier",
        default=None,
    )
    appliesTo: Optional[List[CodeableConcept]] = Field(
        description="Reference range population",
        default=None,
    )
    age: Optional[Range] = Field(
        description="Applicable age range, if relevant",
        default=None,
    )
    text: Optional[String] = Field(
        description="Text based reference range in an observation",
        default=None,
    )
    text_ext: Optional[Element] = Field(
        description="Placeholder element for text extensions",
        default=None,
        alias="_text",
    )

    @field_validator(
        *(
            "text",
            "age",
            "appliesTo",
            "type",
            "high",
            "low",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
        ),
        mode="after",
        check_fields=None
    )
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )


class OnconovaTumorMarkerComponentReferenceRange(BackboneElement):
    """
    Guidance on how to interpret the value by comparison to a normal or recommended range.
    """

    low: Optional[Quantity] = Field(
        description="Low Range, if relevant",
        default=None,
    )
    high: Optional[Quantity] = Field(
        description="High Range, if relevant",
        default=None,
    )
    type: Optional[CodeableConcept] = Field(
        description="Reference range qualifier",
        default=None,
    )
    appliesTo: Optional[List[CodeableConcept]] = Field(
        description="Reference range population",
        default=None,
    )
    age: Optional[Range] = Field(
        description="Applicable age range, if relevant",
        default=None,
    )
    text: Optional[String] = Field(
        description="Text based reference range in an observation",
        default=None,
    )
    text_ext: Optional[Element] = Field(
        description="Placeholder element for text extensions",
        default=None,
        alias="_text",
    )

    @field_validator(
        *(
            "text",
            "age",
            "appliesTo",
            "type",
            "high",
            "low",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
        ),
        mode="after",
        check_fields=None
    )
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )


class OnconovaTumorMarkerComponent(BackboneElement):
    """
    Not used in this profile
    """

    code: Optional[CodeableConcept] = Field(
        description="Type of component observation (code / type)",
        default=None,
    )
    valueQuantity: Optional[Quantity] = Field(
        description="Actual component result",
        default=None,
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Actual component result",
        default=None,
    )
    valueString: Optional[String] = Field(
        description="Actual component result",
        default=None,
    )
    valueString_ext: Optional[Element] = Field(
        description="Placeholder element for valueString extensions",
        default=None,
        alias="_valueString",
    )
    valueBoolean: Optional[Boolean] = Field(
        description="Actual component result",
        default=None,
    )
    valueBoolean_ext: Optional[Element] = Field(
        description="Placeholder element for valueBoolean extensions",
        default=None,
        alias="_valueBoolean",
    )
    valueInteger: Optional[Integer] = Field(
        description="Actual component result",
        default=None,
    )
    valueInteger_ext: Optional[Element] = Field(
        description="Placeholder element for valueInteger extensions",
        default=None,
        alias="_valueInteger",
    )
    valueRange: Optional[Range] = Field(
        description="Actual component result",
        default=None,
    )
    valueRatio: Optional[Ratio] = Field(
        description="Actual component result",
        default=None,
    )
    valueSampledData: Optional[SampledData] = Field(
        description="Actual component result",
        default=None,
    )
    valueTime: Optional[Time] = Field(
        description="Actual component result",
        default=None,
    )
    valueTime_ext: Optional[Element] = Field(
        description="Placeholder element for valueTime extensions",
        default=None,
        alias="_valueTime",
    )
    valueDateTime: Optional[DateTime] = Field(
        description="Actual component result",
        default=None,
    )
    valueDateTime_ext: Optional[Element] = Field(
        description="Placeholder element for valueDateTime extensions",
        default=None,
        alias="_valueDateTime",
    )
    valuePeriod: Optional[Period] = Field(
        description="Actual component result",
        default=None,
    )
    dataAbsentReason: Optional[CodeableConcept] = Field(
        description="Why the component result is missing",
        default=None,
    )
    interpretation: Optional[List[CodeableConcept]] = Field(
        description="High, low, normal, etc.",
        default=None,
    )
    referenceRange: Optional[List[OnconovaTumorMarkerComponentReferenceRange]] = Field(
        description="Provides guide for interpretation of component result",
        default=None,
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(
        *(
            "referenceRange",
            "interpretation",
            "dataAbsentReason",
            "code",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
            "modifierExtension",
            "extension",
        ),
        mode="after",
        check_fields=None
    )
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[
                Quantity,
                CodeableConcept,
                String,
                Boolean,
                Integer,
                Range,
                Ratio,
                SampledData,
                Time,
                DateTime,
                Period,
            ],
            field_name_base="value",
            required=False,
        )


class OnconovaTumorMarker(DomainResource):
    """
        A profile representing a tumor marker observation for a cancer patient, including the type of tumor marker and its value.

    This profile extends the base mCODE [TumorMarkerTest profile](http://hl7.org/fhir/us/mcode/StructureDefinition/mcode-tumor-marker-test) to include specific constraints and requirements for Onconova.

    If relied on the same use context as mCODE, namely for substances found in tissue or blood or other body fluids that may be a sign of cancer or certain benign (non-cancer) conditions measured at the levels of the protein and substance post-RNA protein synthesis (not at genomic level).

    **Conformance:**

    Observation resources representing a tumor marker in the scope of Onconova SHALL conform to this profile. Any resource intended to conform to this profile SHOULD populate `meta.profile` accordingly.
    """

    id: Optional[String] = Field(
        description="Logical id of this artifact",
        default=None,
    )
    id_ext: Optional[Element] = Field(
        description="Placeholder element for id extensions",
        default=None,
        alias="_id",
    )
    meta: Optional[Meta] = Field(
        title="Meta",
        description="Metadata about the resource.",
        default_factory=lambda: Meta(
            profile=[
                "http://onconova.github.io/fhir/StructureDefinition/onconova-tumor-marker"
            ]
        ),
    )
    implicitRules: Optional[Uri] = Field(
        description="A set of rules under which this content was created",
        default=None,
    )
    implicitRules_ext: Optional[Element] = Field(
        description="Placeholder element for implicitRules extensions",
        default=None,
        alias="_implicitRules",
    )
    language: Optional[Code] = Field(
        description="Language of the resource content",
        default=None,
    )
    language_ext: Optional[Element] = Field(
        description="Placeholder element for language extensions",
        default=None,
        alias="_language",
    )
    text: Optional[Narrative] = Field(
        description="Text summary of the resource, for human interpretation",
        default=None,
    )
    contained: Optional[List[Resource]] = Field(
        description="Contained, inline Resources",
        default=None,
    )
    extension: Optional[
        List[
            Annotated[
                Union[RelatedCondition, Extension], Field(union_mode="left_to_right")
            ]
        ]
    ] = Field(
        description="Extension",
        default=None,
    )
    modifierExtension: Optional[List[Extension]] = Field(
        description="Extensions that cannot be ignored",
        default=None,
    )
    identifier: Optional[List[Identifier]] = Field(
        description="Business Identifier for observation",
        default=None,
    )
    basedOn: Optional[List[Reference]] = Field(
        description="Fulfills plan, proposal or order",
        default=None,
    )
    partOf: Optional[List[Reference]] = Field(
        description="Part of referenced event",
        default=None,
    )
    status: Optional[Code] = Field(
        description="Not used in this profile",
        default=None,
    )
    status_ext: Optional[Element] = Field(
        description="Placeholder element for status extensions",
        default=None,
        alias="_status",
    )
    category: Optional[
        List[
            Annotated[
                Union[OnconovaTumorMarkerUsCore, CodeableConcept],
                Field(union_mode="left_to_right"),
            ]
        ]
    ] = Field(
        description="(USCDI) Classification of  type of observation",
        default=None,
    )
    code: Optional[OnconovaTumorMarkerCode] = Field(
        description="(USCDI) Laboratory Test Name",
        default=None,
    )
    subject: Optional[Reference] = Field(
        description="(USCDI) Who and/or what the observation is about",
        default=None,
    )
    focus: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    encounter: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    effectiveDateTime: Optional[DateTime] = Field(
        description="(USCDI) Clinically relevant time/time-period for observation",
        default=None,
    )
    effectiveDateTime_ext: Optional[Element] = Field(
        description="Placeholder element for effectiveDateTime extensions",
        default=None,
        alias="_effectiveDateTime",
    )
    issued: Optional[Instant] = Field(
        description="Not used in this profile",
        default=None,
    )
    issued_ext: Optional[Element] = Field(
        description="Placeholder element for issued extensions",
        default=None,
        alias="_issued",
    )
    performer: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    valueQuantity: Optional[Quantity] = Field(
        description="(USCDI) Result Value",
        default=None,
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="(USCDI) Result Value",
        default=None,
    )
    valueString: Optional[String] = Field(
        description="(USCDI) Result Value",
        default=None,
    )
    valueString_ext: Optional[Element] = Field(
        description="Placeholder element for valueString extensions",
        default=None,
        alias="_valueString",
    )
    valueRatio: Optional[Ratio] = Field(
        description="(USCDI) Result Value",
        default=None,
    )
    dataAbsentReason: Optional[CodeableConcept] = Field(
        description="(USCDI) Why the result is missing",
        default=None,
    )
    interpretation: Optional[List[CodeableConcept]] = Field(
        description="Not used in this profile",
        default=None,
    )
    note: Optional[List[Annotation]] = Field(
        description="Comments about the observation",
        default=None,
    )
    bodySite: Optional[CodeableConcept] = Field(
        description="Not used in this profile",
        default=None,
    )
    method: Optional[CodeableConcept] = Field(
        description="How it was done",
        default=None,
    )
    specimen: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    device: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    referenceRange: Optional[List[OnconovaTumorMarkerReferenceRange]] = Field(
        description="Not used in this profile",
        default=None,
    )
    hasMember: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    derivedFrom: Optional[List[Reference]] = Field(
        description="Related measurements the observation is made from",
        default=None,
    )
    component: Optional[List[OnconovaTumorMarkerComponent]] = Field(
        description="Not used in this profile",
        default=None,
    )
    resourceType: Literal["Observation"] = Field(
        description=None,
        default="Observation",
    )

    @property
    def effective(self):
        return get_type_choice_value_by_base(
            self,
            base="effective",
        )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(
        *(
            "component",
            "derivedFrom",
            "hasMember",
            "referenceRange",
            "device",
            "specimen",
            "method",
            "bodySite",
            "note",
            "interpretation",
            "dataAbsentReason",
            "performer",
            "issued",
            "encounter",
            "focus",
            "subject",
            "code",
            "category",
            "status",
            "partOf",
            "basedOn",
            "identifier",
            "modifierExtension",
            "extension",
            "text",
            "language",
            "implicitRules",
            "meta",
        ),
        mode="after",
        check_fields=None
    )
    @classmethod
    def FHIR_ele_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="hasValue() or (children().count() > id.count())",
            human="All FHIR elements must have a @value or children",
            key="ele-1",
            severity="error",
        )

    @field_validator(
        *("modifierExtension", "extension"), mode="after", check_fields=None
    )
    @classmethod
    def FHIR_ext_1_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="extension.exists() != value.exists()",
            human="Must have either extensions or value[x], not both",
            key="ext-1",
            severity="error",
        )

    @field_validator(*("extension",), mode="after", check_fields=None)
    @classmethod
    def extension_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="extension",
        )

    @field_validator(*("category",), mode="after", check_fields=None)
    @classmethod
    def category_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="category",
        )

    @field_validator(*("referenceRange",), mode="after", check_fields=None)
    @classmethod
    def FHIR_obs_3_constraint_validator(cls, value):
        return validate_element_constraint(
            cls,
            value,
            expression="low.exists() or high.exists() or text.exists()",
            human="Must have at least a low or a high or text",
            key="obs-3",
            severity="error",
        )

    @model_validator(mode="after")
    def effective_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[DateTime],
            field_name_base="effective",
            required=True,
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[Quantity, CodeableConcept, String, Ratio],
            field_name_base="value",
            required=True,
        )

    @model_validator(mode="after")
    def FHIR_dom_2_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="contained.contained.empty()",
            human="If the resource is contained in another resource, it SHALL NOT contain nested Resources",
            key="dom-2",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_dom_3_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="contained.where((('#'+id in (%resource.descendants().reference | %resource.descendants().ofType(canonical) | %resource.descendants().ofType(uri) | %resource.descendants().ofType(url))) or descendants().where(reference = '#').exists() or descendants().where(as(canonical) = '#').exists() or descendants().where(as(canonical) = '#').exists()).not()).trace('unmatched', id).empty()",
            human="If the resource is contained in another resource, it SHALL be referred to from elsewhere in the resource or SHALL refer to the containing resource",
            key="dom-3",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_dom_4_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="contained.meta.versionId.empty() and contained.meta.lastUpdated.empty()",
            human="If a resource is contained in another resource, it SHALL NOT have a meta.versionId or a meta.lastUpdated",
            key="dom-4",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_dom_5_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="contained.meta.security.empty()",
            human="If a resource is contained in another resource, it SHALL NOT have a security label",
            key="dom-5",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_dom_6_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="text.`div`.exists()",
            human="A resource should have narrative for robust management",
            key="dom-6",
            severity="warning",
        )

    @model_validator(mode="after")
    def FHIR_obs_6_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="dataAbsentReason.empty() or value.empty()",
            human="dataAbsentReason SHALL only be present if Observation.value[x] is not present",
            key="obs-6",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_obs_7_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="value.empty() or component.code.where(coding.intersect(%resource.code.coding).exists()).empty()",
            human="If Observation.code is the same as an Observation.component.code then the value element associated with the code SHALL NOT be present",
            key="obs-7",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_us_core_2_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="(component.empty() and hasMember.empty()) implies (dataAbsentReason.exists() or value.exists())",
            human="If there is no component or hasMember element then either a value[x] or a data absent reason must be present",
            key="us-core-2",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_o_tma_req_1_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="subject.exists()",
            human="The subject element is required and must be provided.",
            key="o-tma-req-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_o_tma_req_2_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="effectiveDateTime.exists() and effectiveDateTime.hasValue()",
            human="The effectiveDateTime element is required and must be provided.",
            key="o-tma-req-2",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_o_tma_req_3_constraint_model_validator(self):
        return validate_model_constraint(
            self,
            expression="code.extension('http://onconova.github.io/fhir/StructureDefinition/onconova-ext-tumor-marker-analyte').exists()",
            human="The tumorMarkerAnalyte element is required and must be provided.",
            key="o-tma-req-3",
            severity="error",
        )
