# Code autogenerated by Fhircraft 0.6.4 on 2026-02-20 14:15:12.663564.

from fhircraft.fhir.resources.datatypes.R4.core.condition import (
    Condition,
    ConditionStage,
)
from typing import Annotated, ClassVar, List, Optional, Union
from fhircraft.fhir.resources.datatypes.R4.complex import (
    Age,
    CodeableConcept,
    Meta,
    Period,
    Range,
    Reference,
)
from fhircraft.fhir.resources.datatypes.primitives import DateTime, String
from pydantic import Field, field_validator, model_validator
from fhircraft.fhir.resources.validators import (
    get_type_choice_value_by_base,
    validate_slicing_cardinalities,
    validate_type_choice_element,
)

NoneType = type(None)


class USCoreConditionProblemsHealthConcernsProfile(Condition):
    """
    The US Core Condition Problems and Health Concerns Profile is based upon the core FHIR Condition Resource and meets the  U.S. Core Data for Interoperability (USCDI) v2 'Problems' and 'Health Concerns' requirements and SDOH 'Problems/Health Concerns' requirements.  In version 5.0.0, The US Core Condition Profile has been split into the US Core Condition Encounter Diagnosis Profile and US Core Condition Problems and Health Concerns Profile.  To promote interoperability and adoption through common implementation, this profile defines constraints and extensions on the Condition resource for the minimal set of data to record, search, and fetch information about a condition, diagnosis, or other event, situation, issue, or clinical concept that is documented and categorized as a problem or health concern including information about a Social Determinants of Health-related condition. It identifies which core elements, extensions, vocabularies, and value sets **SHALL** be present in the resource when and constrains the way the elements are used using this profile. It provides the floor for standards development for specific use cases.
    """

    _canonical_url = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition-problems-health-concerns"

    meta: Optional[Meta] = Field(
        title="Meta",
        description="Metadata about the resource.",
        default_factory=lambda: Meta(
            profile=[
                "http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition-problems-health-concerns"
            ]
        ),
    )
    clinicalStatus: Optional[CodeableConcept] = Field(
        description="(USCDI) active | recurrence | relapse | inactive | remission | resolved",
        default=None,
    )
    verificationStatus: Optional[CodeableConcept] = Field(
        description="(USCDI) unconfirmed | provisional | differential | confirmed | refuted | entered-in-error",
        default=None,
    )
    category: Optional[List[CodeableConcept]] = Field(
        description="(USCDI) category codes",
        default=None,
    )
    code: Optional[CodeableConcept] = Field(
        description="(USCDI) Identification of the condition, problem or diagnosis",
        default=None,
    )
    subject: Optional[Reference] = Field(
        description="(USCDI) Who has the condition?",
        default=None,
    )
    onsetDateTime: Optional[DateTime] = Field(
        description="(USCDI) Estimated or actual date,  date-time, or age",
        default=None,
    )
    onsetAge: Optional[Age] = Field(
        description="(USCDI) Estimated or actual date,  date-time, or age",
        default=None,
    )
    onsetPeriod: Optional[Period] = Field(
        description="(USCDI) Estimated or actual date,  date-time, or age",
        default=None,
    )
    onsetRange: Optional[Range] = Field(
        description="(USCDI) Estimated or actual date,  date-time, or age",
        default=None,
    )
    onsetString: Optional[String] = Field(
        description="(USCDI) Estimated or actual date,  date-time, or age",
        default=None,
    )
    abatementDateTime: Optional[DateTime] = Field(
        description="(USCDI) When in resolution/remission",
        default=None,
    )
    abatementAge: Optional[Age] = Field(
        description="(USCDI) When in resolution/remission",
        default=None,
    )
    abatementPeriod: Optional[Period] = Field(
        description="(USCDI) When in resolution/remission",
        default=None,
    )
    abatementRange: Optional[Range] = Field(
        description="(USCDI) When in resolution/remission",
        default=None,
    )
    abatementString: Optional[String] = Field(
        description="(USCDI) When in resolution/remission",
        default=None,
    )
    recordedDate: Optional[DateTime] = Field(
        description="(USCDI) Date record was first recorded",
        default=None,
    )

    @property
    def onset(self):
        return get_type_choice_value_by_base(
            self,
            base="onset",
        )

    @property
    def abatement(self):
        return get_type_choice_value_by_base(
            self,
            base="abatement",
        )

    @field_validator(*("category",), mode="after", check_fields=None)
    @classmethod
    def category_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="category",
        )

    @model_validator(mode="after")
    def onset_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=["DateTime", "Age", "Period", "Range", "String"],
            field_name_base="onset",
            required=False,
            non_allowed_types=[],
        )

    @model_validator(mode="after")
    def abatement_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=["DateTime", "Age", "Period", "Range", "String"],
            field_name_base="abatement",
            required=False,
            non_allowed_types=[],
        )
