# Code autogenerated by Fhircraft 0.5.0 on 2026-04-15 15:32:44.844703.
# pyright: reportIncompatibleVariableOverride=false

from fhircraft.fhir.resources.datatypes.R4.core.observation import (
    Observation,
    ObservationComponent,
    ObservationReferenceRange,
)
from typing import Annotated, ClassVar, List, Optional, Union
from fhircraft.fhir.resources.datatypes.R4.complex import (
    CodeableConcept,
    Coding,
    Period,
    Quantity,
    Range,
    Ratio,
    Reference,
    SampledData,
)
from fhircraft.fhir.resources.base import FHIRSliceModel, FhirBaseModelKind
from pydantic import Field, field_validator, model_validator
from fhircraft.fhir.resources.validators import (
    get_type_choice_value_by_base,
    validate_FHIR_element_fixed_value,
    validate_FHIR_element_pattern,
    validate_element_constraint,
    validate_model_constraint,
    validate_slicing_cardinalities,
    validate_type_choice_element,
)
from fhircraft.fhir.resources.datatypes.R4.primitive import (
    Boolean,
    DateTime,
    Integer,
    String,
    Time,
)
import fhircraft.fhir.resources.datatypes.R4.primitive as fhir

NoneType = type(None)


class ObservationVitalsignsCoding(Coding):
    """
    A reference to a code defined by a terminology system.
    """

    system: Optional[fhir.uri] = Field(
        description="The identification of the code system that defines the meaning of the symbol in the code.",
        default_factory=lambda: "http://terminology.hl7.org/CodeSystem/observation-category",
    )
    code: Optional[fhir.code] = Field(
        description="A symbol in syntax defined by the system. The symbol may be a predefined code or an expression in a syntax defined by the coding system (e.g. post-coordination).",
        default_factory=lambda: "vital-signs",
    )

    @field_validator(*("system",), mode="after", check_fields=None)
    @classmethod
    def FHIR_system_fixed_value_constraint(cls, value):
        return validate_FHIR_element_fixed_value(
            cls,
            value,
            constant="http://terminology.hl7.org/CodeSystem/observation-category",
        )

    @field_validator(*("code",), mode="after", check_fields=None)
    @classmethod
    def FHIR_code_fixed_value_constraint(cls, value):
        return validate_FHIR_element_fixed_value(
            cls,
            value,
            constant="vital-signs",
        )


class ObservationVitalsignsVSCat(CodeableConcept, FHIRSliceModel):
    """
    A code that classifies the general type of observation being made.
    """

    min_cardinality: ClassVar[int] = 1
    max_cardinality: ClassVar[int | None] = 1

    coding: Optional[List[ObservationVitalsignsCoding]] = Field(
        description="A reference to a code defined by a terminology system.",
        default=None,
    )


class ObservationVitalsignsComponent(ObservationComponent):
    """
    Used when reporting systolic and diastolic blood pressure.
    """

    code: Optional[CodeableConcept] = Field(
        description='Describes what was observed. Sometimes this is called the observation "code".',
        default=None,
    )
    valueQuantity: Optional[Quantity] = Field(
        description="Vital Sign Value recorded with UCUM.",
        default=None,
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Vital Sign Value recorded with UCUM.",
        default=None,
    )
    valueString: Optional[fhir.string] = Field(
        description="Vital Sign Value recorded with UCUM.",
        default=None,
    )
    valueBoolean: Optional[fhir.boolean] = Field(
        description="Vital Sign Value recorded with UCUM.",
        default=None,
    )
    valueInteger: Optional[fhir.integer] = Field(
        description="Vital Sign Value recorded with UCUM.",
        default=None,
    )
    valueRange: Optional[Range] = Field(
        description="Vital Sign Value recorded with UCUM.",
        default=None,
    )
    valueRatio: Optional[Ratio] = Field(
        description="Vital Sign Value recorded with UCUM.",
        default=None,
    )
    valueSampledData: Optional[SampledData] = Field(
        description="Vital Sign Value recorded with UCUM.",
        default=None,
    )
    valueTime: Optional[fhir.time_] = Field(
        description="Vital Sign Value recorded with UCUM.",
        default=None,
    )
    valueDateTime: Optional[fhir.dateTime] = Field(
        description="Vital Sign Value recorded with UCUM.",
        default=None,
    )
    valuePeriod: Optional[Period] = Field(
        description="Vital Sign Value recorded with UCUM.",
        default=None,
    )
    dataAbsentReason: Optional[CodeableConcept] = Field(
        description="Provides a reason why the expected value in the element Observation.component.value[x] is missing.",
        default=None,
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[
                "Quantity",
                "CodeableConcept",
                "String",
                "Boolean",
                "Integer",
                "Range",
                "Ratio",
                "SampledData",
                "Time",
                "DateTime",
                "Period",
            ],
            field_name_base="value",
            required=False,
        )

    @model_validator(mode="after")
    def FHIR_vs_3_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="value.exists() or dataAbsentReason.exists()",
            human="If there is no a value a data absent reason must be present",
            key="vs-3",
            severity="error",
        )


class ObservationVitalsigns(Observation):
    """
    The FHIR Vitals Signs profile sets minimum expectations for the Observation Resource to record, search and fetch the vital signs associated with a patient.
    """

    _abstract = True
    _canonical_url = "http://hl7.org/fhir/StructureDefinition/vitalsigns"

    status: Optional[fhir.code] = Field(
        description="The status of the result value.",
        default=None,
    )
    category: Optional[List[Union[ObservationVitalsignsVSCat, CodeableConcept]]] = (
        Field(
            description="Classification of  type of observation",
            default=None,
        )
    )
    code: Optional[CodeableConcept] = Field(
        description="Coded Responses from C-CDA Vital Sign Results.",
        default=None,
    )
    subject: Optional[Reference] = Field(
        description="The patient, or group of patients, location, or device this observation is about and into whose record the observation is placed. If the actual focus of the observation is different from the subject (or a sample of, part, or region of the subject), the `focus` element or the `code` itself specifies the actual focus of the observation.",
        default=None,
    )
    effectiveDateTime: Optional[fhir.dateTime] = Field(
        description="Often just a dateTime for Vital Signs.",
        default=None,
    )
    effectivePeriod: Optional[Period] = Field(
        description="Often just a dateTime for Vital Signs.",
        default=None,
    )
    valueQuantity: Optional[Quantity] = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueCodeableConcept: Optional[CodeableConcept] = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueString: Optional[fhir.string] = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueBoolean: Optional[fhir.boolean] = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueInteger: Optional[fhir.integer] = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueRange: Optional[Range] = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueRatio: Optional[Ratio] = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueSampledData: Optional[SampledData] = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueTime: Optional[fhir.time_] = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueDateTime: Optional[fhir.dateTime] = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valuePeriod: Optional[Period] = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    dataAbsentReason: Optional[CodeableConcept] = Field(
        description="Provides a reason why the expected value in the element Observation.value[x] is missing.",
        default=None,
    )
    hasMember: Optional[List[Reference]] = Field(
        description="Used when reporting vital signs panel components.",
        default=None,
    )
    derivedFrom: Optional[List[Reference]] = Field(
        description="The target resource that represents a measurement from which this observation value is derived. For example, a calculated anion gap or a fetal measurement based on an ultrasound image.",
        default=None,
    )
    component: Optional[List[ObservationVitalsignsComponent]] = Field(
        description="Used when reporting systolic and diastolic blood pressure.",
        default=None,
    )

    @property
    def effective(self):
        return get_type_choice_value_by_base(
            self,
            base="effective",
        )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @field_validator(*("category",), mode="after", check_fields=None)
    @classmethod
    def category_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="category",
        )

    @model_validator(mode="after")
    def effective_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=["DateTime", "Period"],
            field_name_base="effective",
            required=True,
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[
                "Quantity",
                "CodeableConcept",
                "String",
                "Boolean",
                "Integer",
                "Range",
                "Ratio",
                "SampledData",
                "Time",
                "DateTime",
                "Period",
            ],
            field_name_base="value",
            required=False,
        )

    @model_validator(mode="after")
    def FHIR_vs_1_constraint_validator(self):
        return validate_element_constraint(
            self,
            elements="effectivePeriod",
            expression="($this as dateTime).toString().length() >= 8",
            human="if Observation.effective[x] is dateTime and has a value then that value shall be precise to the day",
            key="vs-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_vs_3_constraint_validator(self):
        return validate_element_constraint(
            self,
            elements="component",
            expression="value.exists() or dataAbsentReason.exists()",
            human="If there is no a value a data absent reason must be present",
            key="vs-3",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_vs_2_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="(component.empty() and hasMember.empty()) implies (dataAbsentReason.exists() or value.exists())",
            human="If there is no component or hasMember element then either a value[x] or a data absent reason must be present.",
            key="vs-2",
            severity="error",
        )


class ObservationVitalspanelVitalsPanelCode(Coding, FHIRSliceModel):
    """
    A reference to a code defined by a terminology system.
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = None

    system: Optional[fhir.uri] = Field(
        description="The identification of the code system that defines the meaning of the symbol in the code.",
        default_factory=lambda: "http://loinc.org",
    )
    code: Optional[fhir.code] = Field(
        description="A symbol in syntax defined by the system. The symbol may be a predefined code or an expression in a syntax defined by the coding system (e.g. post-coordination).",
        default_factory=lambda: "85353-1",
    )

    @field_validator(*("system",), mode="after", check_fields=None)
    @classmethod
    def FHIR_system_fixed_value_constraint(cls, value):
        return validate_FHIR_element_fixed_value(
            cls,
            value,
            constant="http://loinc.org",
        )

    @field_validator(*("code",), mode="after", check_fields=None)
    @classmethod
    def FHIR_code_fixed_value_constraint(cls, value):
        return validate_FHIR_element_fixed_value(
            cls,
            value,
            constant="85353-1",
        )


class ObservationVitalspanelCode(CodeableConcept):
    """
    Vital Signs Panel.
    """

    coding: Optional[List[Union[ObservationVitalspanelVitalsPanelCode, Coding]]] = (
        Field(
            description="Code defined by a terminology system",
            default=None,
        )
    )

    @field_validator(*("coding",), mode="after", check_fields=None)
    @classmethod
    def coding_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="coding",
        )


class ObservationVitalspanel(ObservationVitalsigns):
    """
    This profile defines the top-level grouping structure for a set of vital signs. It has no value in Observation.valueQuantity ; instead, it just includes related links (with type=has-member) to the Observations in this set (e.g. respiratory rate, heart rate, BP).
    """

    _canonical_url = "http://hl7.org/fhir/StructureDefinition/vitalspanel"

    code: Optional[ObservationVitalspanelCode] = Field(
        description="Vital Signs Panel.",
        default=None,
    )
    valueQuantity: None = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueCodeableConcept: None = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueString: None = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueBoolean: None = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueInteger: None = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueRange: None = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueRatio: None = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueSampledData: None = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueTime: None = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valueDateTime: None = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    valuePeriod: None = Field(
        description="Vital Signs value are recorded using the Quantity data type. For supporting observations such as Cuff size could use other datatypes such as CodeableConcept.",
        default=None,
    )
    hasMember: Optional[List[Reference]] = Field(
        description="Used when reporting vital signs panel components.",
        default=None,
    )

    @property
    def value(self):
        return get_type_choice_value_by_base(
            self,
            base="value",
        )

    @model_validator(mode="after")
    def value_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=[
                "Quantity",
                "CodeableConcept",
                "String",
                "Boolean",
                "Integer",
                "Range",
                "Ratio",
                "SampledData",
                "Time",
                "DateTime",
                "Period",
            ],
            field_name_base="value",
            required=False,
        )

    @model_validator(mode="after")
    def FHIR_vs_2_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="(component.empty() and hasMember.empty()) implies (dataAbsentReason.exists() or value.exists())",
            human="If there is no component or hasMember element then either a value[x] or a data absent reason must be present.",
            key="vs-2",
            severity="error",
        )


class OnconovaVitalSignsPanelBodyTemperature(Reference, FHIRSliceModel):
    """
    Used when reporting vital signs panel components.
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1

    pass


class OnconovaVitalSignsPanelBodyHeight(Reference, FHIRSliceModel):
    """
    Used when reporting vital signs panel components.
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1

    pass


class OnconovaVitalSignsPanelBodyWeight(Reference, FHIRSliceModel):
    """
    Used when reporting vital signs panel components.
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1

    pass


class OnconovaVitalSignsPanelBmi(Reference, FHIRSliceModel):
    """
    Used when reporting vital signs panel components.
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1

    pass


class OnconovaVitalSignsPanelBloodPressure(Reference, FHIRSliceModel):
    """
    Used when reporting vital signs panel components.
    """

    min_cardinality: ClassVar[int] = 0
    max_cardinality: ClassVar[int | None] = 1

    pass


class OnconovaVitalSignsPanel(ObservationVitalspanel):
    """
    This profile defines the top-level grouping structure for a set of vital signs. It has no value in Observation.valueQuantity ; instead, it just includes related links (with type=has-member) to the Observations in this set (e.g. respiratory rate, heart rate, BP).
    """

    _canonical_url = (
        "http://onconova.github.io/fhir/StructureDefinition/onconova-vital-signs-panel"
    )

    status: Optional[fhir.code] = Field(
        description="Not used in this profile",
        default=None,
    )
    code: Optional[CodeableConcept] = Field(
        description="Vital Signs Panel.",
        default_factory=lambda: CodeableConcept(
            coding=[Coding(code="85353-1", system="http://loinc.org")]
        ),
    )
    focus: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    encounter: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    issued: Optional[fhir.instant] = Field(
        description="Not used in this profile",
        default=None,
    )
    performer: Optional[List[Reference]] = Field(
        description="Not used in this profile",
        default=None,
    )
    interpretation: Optional[List[CodeableConcept]] = Field(
        description="Not used in this profile",
        default=None,
    )
    bodySite: Optional[CodeableConcept] = Field(
        description="Not used in this profile",
        default=None,
    )
    specimen: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    device: Optional[Reference] = Field(
        description="Not used in this profile",
        default=None,
    )
    referenceRange: Optional[List[ObservationReferenceRange]] = Field(
        description="Not used in this profile",
        default=None,
    )
    hasMember: Optional[List[Reference]] = Field(
        description="Used when reporting vital signs panel components",
        default=None,
    )
    component: Optional[List[ObservationVitalsignsComponent]] = Field(
        description="Not used in this profile",
        default=None,
    )

    @property
    def effective(self):
        return get_type_choice_value_by_base(
            self,
            base="effective",
        )

    @field_validator(*("code",), mode="after", check_fields=None)
    @classmethod
    def FHIR_code_pattern_constraint(cls, value):
        return validate_FHIR_element_pattern(
            cls,
            value,
            pattern=CodeableConcept(
                coding=[Coding(code="85353-1", system="http://loinc.org")]
            ),
        )

    @field_validator(*("hasMember",), mode="after", check_fields=None)
    @classmethod
    def hasMember_slicing_cardinality_validator(cls, value):
        return validate_slicing_cardinalities(
            cls,
            value,
            field_name="hasMember",
        )

    @model_validator(mode="after")
    def effective_type_choice_validator(self):
        return validate_type_choice_element(
            self,
            field_types=["DateTime"],
            field_name_base="effective",
            required=True,
        )

    @model_validator(mode="after")
    def FHIR_obs_3_constraint_validator(self):
        return validate_element_constraint(
            self,
            elements="referenceRange",
            expression="low.exists() or high.exists() or text.exists()",
            human="Must have at least a low or a high or text",
            key="obs-3",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_vs_1_constraint_validator(self):
        return validate_element_constraint(
            self,
            elements="effectiveDateTime",
            expression="($this as dateTime).toString().length() >= 8",
            human="if Observation.effective[x] is dateTime and has a value then that value shall be precise to the day",
            key="vs-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_vs_3_constraint_validator(self):
        return validate_element_constraint(
            self,
            elements="component",
            expression="value.exists() or dataAbsentReason.exists()",
            human="If there is no a value a data absent reason must be present",
            key="vs-3",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_o_vit_req_1_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="subject.exists()",
            human="The subject element is required and must be provided.",
            key="o-vit-req-1",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_o_vit_req_2_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="effectiveDateTime.exists() and effectiveDateTime.hasValue()",
            human="The effectiveDateTime element is required and must be provided.",
            key="o-vit-req-2",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_o_vit_req_3_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="hasMember.exists() and hasMember.count() > 0",
            human="At least one vital sign profile must be referenced.",
            key="o-vit-req-3",
            severity="error",
        )

    @model_validator(mode="after")
    def FHIR_o_vit_req_4_constraint_validator(self):
        return validate_model_constraint(
            self,
            expression="value.exists().not()",
            human="The value[x] element must not be set for the vitals panel.",
            key="o-vit-req-4",
            severity="error",
        )
